import type {
  StudyAmendmentVerdict,
  StudyChoiceFactor,
  StudyClaimStatus,
  StudyNoticeCode,
  StudyPassage,
  StudyPassageState,
  StudyPrinciple,
  StudyStats,
  StudyStopReason,
} from './study-types.js';

/** Languages the study writes its dossier in; any other language gets the English labels. */
export type StudyLabelLanguage =
  | 'en'
  | 'fr'
  | 'es'
  | 'de'
  | 'pt'
  | 'ja'
  | 'zh'
  | 'ko'
  | 'ru'
  | 'ar'
  | 'hi';

type Collection =
  | 'analogues'
  | 'capabilities'
  | 'observations'
  | 'pieces'
  | 'chain'
  | 'historicalChoices'
  | 'advances'
  | 'leadVerdicts'
  | 'independentLeads'
  | 'references'
  | 'constraints'
  | 'revisableDecisions'
  | 'combinations'
  | 'architectures'
  | 'threeStates'
  | 'noveltyClaims'
  | 'experiments'
  | 'cards';

/** The words of a dossier. Notices take their detail in place of `{detail}`. */
export interface StudyLabels {
  /** Between a label and its value (a no-break space before the colon in French). */
  sep: string;
  /** Between the values of a list. */
  list: string;
  guidingQuestion: string;
  study: string;
  charter: string;
  object: string;
  question: string;
  objective: string;
  needs: string;
  leads: string;
  leadsNote: string;
  outOfScope: string;
  charterHash: string;
  amendments: string;
  amendmentVerdicts: Record<StudyAmendmentVerdict, string>;
  refused: string;
  notices: string;
  noticeTexts: Record<StudyNoticeCode, string>;
  stopReasons: Record<StudyStopReason, string>;
  principle: string;
  principleText: string;
  passages: string;
  passage: string;
  state: string;
  passageNames: Record<StudyPassage, string>;
  passageStates: Record<StudyPassageState['state'], string>;
  collections: Record<Collection, string>;
  kinds: Record<'behaviour' | 'use' | 'variation' | 'failure', string>;
  conditions: string;
  era: string;
  function: string;
  inputs: string;
  outputs: string;
  relations: string;
  unknowns: string;
  parent: string;
  pieces: string;
  factors: string;
  factorNames: Record<StudyChoiceFactor, string>;
  date: string;
  evidence: string;
  availability: string;
  otherDomain: string;
  verdicts: Record<'relevant' | 'partlyRelevant' | 'notRelevant', string>;
  unverifiedLead: string;
  toolKinds: Record<'mathematical' | 'technical' | 'other', string>;
  constraintStates: Record<'remains' | 'weakened' | 'newRequirement', string>;
  because: string;
  opens: string;
  states: Record<'atItsTime' | 'currentBest' | 'proposal', string>;
  enables: string;
  exchange: string;
  cost: string;
  changes: string;
  changeKinds: Record<'representation' | 'distribution' | 'responsibilities', string>;
  designLeads: string;
  mechanism: string;
  benefit: string;
  addedCost: string;
  counterexample: string;
  chainCoverage: string;
  uncovered: string;
  predictions: string;
  architecture: string;
  priorArt: string;
  priorArtVerdicts: Record<'novel' | 'partlyNovel' | 'exists', string>;
  decides: string;
  protocol: string;
  measures: string;
  criteria: string;
  expected: string;
  wholeChain: string;
  yes: string;
  no: string;
  /** The eleven fields of a mechanism card, in order. */
  cardFields: [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];
  toFill: string;
  error: string;
  statuses: Record<StudyClaimStatus, string>;
  noveltyToVerify: string;
  declared: string;
  unchecked: string;
  serves: string;
  driftLog: string;
  driftBy: Record<'guardian' | 'schema', string>;
  noDrift: string;
  sources: string;
  via: string;
  noResults: string;
  statistics: string;
  stats: Record<Exclude<keyof StudyStats, 'byStatus' | 'searchesSkipped'>, string>;
  /** Appended to the guiding question when the charter names no capability. */
  capabilityQuestion: string;
  /** Appended to it when the charter names one (`{capability}`). */
  capabilityAim: string;
  capabilityAimed: string;
  noCapabilityNamed: string;
  analoguesNamed: string;
  newCapability: string;
  /** What an improvement makes faster or cheaper. */
  improves: string;
  forWhom: string;
  liftedConstraint: string;
  hardToday: string;
  principleChange: string;
  principles: Record<StudyPrinciple, string>;
  componentsAssembly: string;
  assembly: string;
  gives: string;
  capabilityOpened: string;
  pattern: string;
  components: string;
  domain: string;
  /** Points from components to assembly to capability, in the reading direction. */
  arrow: string;
  architectureKinds: Record<'capability' | 'improvement', string>;
  judgedImprovement: string;
  none: string;
}

const en: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'If we had to meet today’s needs with the knowledge and techniques available today, how would we organise this object?',
  study: 'Study',
  charter: 'Charter',
  object: 'Object',
  question: 'Guiding question',
  objective: 'Objective',
  needs: 'Needs and criteria of today',
  leads: 'The user’s leads',
  leadsNote: 'examples to verify, not truths',
  outOfScope: 'Out of scope',
  charterHash: 'Charter hash (SHA-256)',
  amendments: 'Amendments',
  amendmentVerdicts: {
    refines: 'refines the objective, accepted',
    conflicts: 'conflicts with the charter',
    changesObjective: 'changes the objective',
    unclassified: 'could not be classified',
  },
  refused: 'refused',
  notices: 'Before reading',
  noticeTexts: {
    analoguesNotDeconstructed: 'Breakthroughs not deconstructed: {detail}.',
    noCapability: 'No architecture aims at a new capability: the design offers only improvements.',
    noSources:
      'The study had no search source: no claim could be established, and no novelty checked against prior art.',
    stopped: 'The run was stopped ({detail}); this dossier is partial.',
    failed: 'The run failed ({detail}); this dossier is partial.',
    cancelled: 'The run was cancelled; this dossier is partial.',
    passagesNotRun: 'Passages not run: {detail}.',
    uncheckedItems: 'Items the guardian has not judged yet, in: {detail}.',
    searchesSkipped: 'The search budget ran out: {detail}.',
    leadsNotVerified: 'Leads without a verdict: {detail}.',
    noveltiesToVerify: 'Novelties still to verify against prior art: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'model call limit',
    timeoutMs: 'time limit',
    policy: 'budget policy',
  },
  principle: 'Principle',
  principleText:
    'Observe the object, enter its mechanisms, understand its pieces and how they interact. Find the problems its construction answered, with the means and knowledge of its time. Study the advances since, in its domain and in nearby ones. Use this understanding to imagine another organisation of the system, and design the experiments that would test it as a whole. An established claim cites a result retrieved during this study; a hypothesis is plausible but not documented here; a novelty is checked against prior art.',
  passages: 'Passages',
  passage: 'Passage',
  state: 'State',
  passageNames: {
    observe: 'Observe',
    decompose: 'Decompose',
    historicalChoices: 'Understand the choices of their time',
    changes: 'Examine what changed',
    cross: 'Cross past and present',
    design: 'Design several organisations',
    confront: 'Confront',
  },
  passageStates: {
    complete: 'complete',
    partial: 'partial',
    unchecked: 'not judged by the guardian',
    notRun: 'not run',
  },
  collections: {
    analogues: 'Breakthroughs by assembly',
    capabilities: 'Candidate new capabilities',
    observations: 'Observations',
    pieces: 'Pieces and their unknowns',
    chain: 'The whole chain',
    historicalChoices: 'Choices and their conditions',
    advances: 'Advances since',
    leadVerdicts: 'The user’s leads, verified',
    independentLeads: 'Leads found beyond them',
    references: 'Best current realisations',
    constraints: 'Constraints',
    revisableDecisions: 'Decisions that became revisable',
    combinations: 'Combinations',
    architectures: 'Architectures',
    threeStates: 'Three states',
    noveltyClaims: 'What is novel, and what is not',
    experiments: 'Experiments',
    cards: 'Mechanism cards',
  },
  kinds: { behaviour: 'Behaviour', use: 'Use', variation: 'Variation', failure: 'Failure' },
  conditions: 'Conditions',
  era: 'Era',
  function: 'Function',
  inputs: 'Inputs',
  outputs: 'Outputs',
  relations: 'Relations',
  unknowns: 'Unknowns',
  parent: 'Detail of',
  pieces: 'Pieces',
  factors: 'Conditions of the time',
  factorNames: {
    hardware: 'hardware',
    tools: 'tools',
    uses: 'uses',
    knowledge: 'knowledge',
    costs: 'costs',
    compatibility: 'compatibility',
    other: 'other',
  },
  date: 'Date',
  evidence: 'Evidence',
  availability: 'Availability',
  otherDomain: 'from another domain',
  verdicts: {
    relevant: 'relevant',
    partlyRelevant: 'partly relevant',
    notRelevant: 'not relevant',
  },
  unverifiedLead: 'no verdict',
  toolKinds: { mathematical: 'mathematical', technical: 'technical', other: 'other' },
  constraintStates: {
    remains: 'Remain',
    weakened: 'Have weakened',
    newRequirement: 'New requirements',
  },
  because: 'Because',
  opens: 'Opens',
  states: {
    atItsTime: 'The object at its time',
    currentBest: 'Best current realisations',
    proposal: 'Our proposal',
  },
  enables: 'What A lets B do',
  exchange: 'What they exchange',
  cost: 'What it costs',
  changes: 'Changes',
  changeKinds: {
    representation: 'the representation',
    distribution: 'the distribution of work',
    responsibilities: 'the responsibilities',
  },
  designLeads: 'Design leads',
  mechanism: 'Mechanism',
  benefit: 'Expected benefit',
  addedCost: 'Added cost',
  counterexample: 'Possible counterexample',
  chainCoverage: 'Across the whole chain',
  uncovered: 'Stages not covered',
  predictions: 'Predictions',
  architecture: 'Architecture',
  priorArt: 'Prior art',
  priorArtVerdicts: { novel: 'novel', partlyNovel: 'partly novel', exists: 'already exists' },
  decides: 'Decides between',
  protocol: 'Protocol',
  measures: 'Measures',
  criteria: 'Criteria',
  expected: 'Expected results',
  wholeChain: 'Tests the whole chain',
  yes: 'yes',
  no: 'no',
  cardFields: [
    'Observation',
    'Mechanism understood',
    'Unknown',
    'Historical choice',
    'Evolution',
    'New possibility',
    'Proposed combination',
    'Prediction',
    'Experiment',
    'Result and error',
    'Conclusion and memory',
  ],
  toFill: 'to fill once the experiment has run',
  error: 'Error',
  statuses: { established: 'established', hypothesis: 'hypothesis', novelty: 'novelty' },
  noveltyToVerify: 'novelty to verify',
  declared: 'declared',
  unchecked: 'not judged by the guardian',
  serves: 'Serves',
  driftLog: 'Drift log',
  driftBy: { guardian: 'off the objective', schema: 'refused by the schema' },
  noDrift: 'No item left the objective.',
  sources: 'Sources',
  via: 'via',
  noResults: 'No result was retrieved.',
  statistics: 'Statistics',
  stats: {
    runs: 'Runs',
    modelCalls: 'Model calls',
    searches: 'Searches',
    results: 'Results retrieved',
    items: 'Items',
    rejected: 'Items rejected',
    downgraded: 'Statuses lowered',
    noveltiesToVerify: 'Novelties to verify',
    redos: 'Passages redone',
    loops: 'Passages reopened',
  },
  capabilityQuestion:
    'Which change of principle would make possible something difficult today, not only faster?',
  capabilityAim:
    'Which change of principle would make this possible, difficult today: {capability}?',
  capabilityAimed: 'Capability aimed at',
  noCapabilityNamed: 'none named: the study proposes candidates',
  analoguesNamed: 'Breakthroughs to deconstruct',
  newCapability: 'New capability aimed at',
  improves: 'What improves',
  forWhom: 'For whom',
  liftedConstraint: 'Constraint lifted',
  hardToday: 'Why it is hard today',
  principleChange: 'Change of principle',
  principles: {
    representation: 'representation',
    distribution: 'distribution of work',
    responsibility: 'responsibility',
    trust: 'trust',
    verification: 'what is verified',
    other: 'other',
  },
  componentsAssembly: 'Components → assembly',
  assembly: 'assembly',
  gives: 'gives the others',
  capabilityOpened: 'Capability opened',
  pattern: 'Assembly pattern',
  components: 'Components',
  domain: 'Domain',
  arrow: '→',
  architectureKinds: {
    capability: 'new capability',
    improvement: 'improvement: faster or cheaper',
  },
  judgedImprovement: 'the guardian judged it only faster or cheaper',
  none: 'none',
};

// French puts a no-break space (U+00A0) before `: ; ? !`.
const fr: StudyLabels = {
  sep: ' : ',
  list: ' ; ',
  guidingQuestion:
    'Si nous devions satisfaire les besoins d’aujourd’hui avec les connaissances et les techniques disponibles aujourd’hui, comment organiserions-nous cet objet ?',
  study: 'Étude',
  charter: 'Charte',
  object: 'Objet',
  question: 'Question directrice',
  objective: 'Objectif',
  needs: 'Besoins et critères d’aujourd’hui',
  leads: 'Pistes de l’utilisateur',
  leadsNote: 'des exemples à vérifier, non des vérités',
  outOfScope: 'Hors du périmètre',
  charterHash: 'Empreinte de la charte (SHA-256)',
  amendments: 'Amendements',
  amendmentVerdicts: {
    refines: 'précise l’objectif, accepté',
    conflicts: 'contredit la charte',
    changesObjective: 'change l’objectif',
    unclassified: 'n’a pas pu être classé',
  },
  refused: 'refusé',
  notices: 'Avant de lire',
  noticeTexts: {
    analoguesNotDeconstructed: 'Ruptures non déconstruites : {detail}.',
    noCapability:
      'Aucune architecture ne vise une capacité nouvelle : la conception n’offre que des améliorations.',
    noSources:
      'L’étude n’avait aucune source de recherche : aucune affirmation n’a pu être établie, et aucune nouveauté confrontée à l’existant.',
    stopped: 'L’exécution a été arrêtée ({detail}) ; ce dossier est partiel.',
    failed: 'L’exécution a échoué ({detail}) ; ce dossier est partiel.',
    cancelled: 'L’exécution a été annulée ; ce dossier est partiel.',
    passagesNotRun: 'Passages non exécutés : {detail}.',
    uncheckedItems: 'Éléments que le gardien n’a pas encore jugés, dans : {detail}.',
    searchesSkipped: 'Le budget de recherches est épuisé : {detail}.',
    leadsNotVerified: 'Pistes sans verdict : {detail}.',
    noveltiesToVerify: 'Nouveautés encore à confronter à l’existant : {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'limite d’appels au modèle',
    timeoutMs: 'limite de durée',
    policy: 'politique de budget',
  },
  principle: 'Le principe',
  principleText:
    'Observer l’objet, entrer dans ses mécanismes, comprendre ses composants et leurs interactions. Retrouver les problèmes auxquels sa construction répondait, avec les moyens et les connaissances de son époque. Étudier les avancées intervenues depuis, dans son domaine et dans les domaines voisins. Utiliser cette compréhension pour imaginer une autre organisation du système, et concevoir les expériences qui l’éprouveraient dans son ensemble. Une connaissance établie cite un résultat obtenu pendant cette étude ; une hypothèse est plausible mais non documentée ici ; une nouveauté est confrontée à l’existant.',
  passages: 'Les passages',
  passage: 'Passage',
  state: 'État',
  passageNames: {
    observe: 'Observer',
    decompose: 'Décomposer',
    historicalChoices: 'Comprendre les choix d’époque',
    changes: 'Examiner ce qui a changé',
    cross: 'Croiser passé et présent',
    design: 'Concevoir plusieurs organisations',
    confront: 'Confronter',
  },
  passageStates: {
    complete: 'terminé',
    partial: 'partiel',
    unchecked: 'non jugé par le gardien',
    notRun: 'non exécuté',
  },
  collections: {
    analogues: 'Ruptures par assemblage',
    capabilities: 'Capacités nouvelles candidates',
    observations: 'Observations',
    pieces: 'Pièces et inconnues',
    chain: 'La chaîne complète',
    historicalChoices: 'Choix et conditions d’époque',
    advances: 'Avancées depuis',
    leadVerdicts: 'Pistes de l’utilisateur, vérifiées',
    independentLeads: 'Pistes trouvées au-delà',
    references: 'Meilleures réalisations actuelles',
    constraints: 'Contraintes',
    revisableDecisions: 'Décisions devenues révisables',
    combinations: 'Combinaisons',
    architectures: 'Architectures',
    threeStates: 'Trois états',
    noveltyClaims: 'Ce qui est nouveau, et ce qui ne l’est pas',
    experiments: 'Expériences',
    cards: 'Fiches de mécanisme',
  },
  kinds: { behaviour: 'Comportement', use: 'Usage', variation: 'Variation', failure: 'Panne' },
  conditions: 'Conditions',
  era: 'Époque',
  function: 'Fonction',
  inputs: 'Entrées',
  outputs: 'Sorties',
  relations: 'Relations',
  unknowns: 'Inconnues',
  parent: 'Détail de',
  pieces: 'Pièces',
  factors: 'Conditions d’époque',
  factorNames: {
    hardware: 'matériel',
    tools: 'outils',
    uses: 'usages',
    knowledge: 'connaissances',
    costs: 'coûts',
    compatibility: 'compatibilité',
    other: 'autre',
  },
  date: 'Date',
  evidence: 'Preuve',
  availability: 'Disponibilité',
  otherDomain: 'd’un autre domaine',
  verdicts: {
    relevant: 'pertinente',
    partlyRelevant: 'partiellement pertinente',
    notRelevant: 'non pertinente',
  },
  unverifiedLead: 'sans verdict',
  toolKinds: { mathematical: 'mathématique', technical: 'technique', other: 'autre' },
  constraintStates: {
    remains: 'Subsistent',
    weakened: 'Se sont atténuées',
    newRequirement: 'Nouvelles exigences',
  },
  because: 'Parce que',
  opens: 'Ouvre',
  states: {
    atItsTime: 'L’objet à son époque',
    currentBest: 'Meilleures réalisations actuelles',
    proposal: 'Notre proposition',
  },
  enables: 'Ce que A permet à B',
  exchange: 'Ce qu’ils échangent',
  cost: 'Ce que cela coûte',
  changes: 'Change',
  changeKinds: {
    representation: 'la représentation',
    distribution: 'la répartition du travail',
    responsibilities: 'les responsabilités',
  },
  designLeads: 'Pistes de conception',
  mechanism: 'Mécanisme',
  benefit: 'Bénéfice attendu',
  addedCost: 'Coût ajouté',
  counterexample: 'Contre-exemple possible',
  chainCoverage: 'Sur toute la chaîne',
  uncovered: 'Étapes non couvertes',
  predictions: 'Prédictions',
  architecture: 'Architecture',
  priorArt: 'Existant',
  priorArtVerdicts: { novel: 'nouveau', partlyNovel: 'en partie nouveau', exists: 'existe déjà' },
  decides: 'Départage',
  protocol: 'Protocole',
  measures: 'Mesures',
  criteria: 'Critères',
  expected: 'Résultats attendus',
  wholeChain: 'Éprouve toute la chaîne',
  yes: 'oui',
  no: 'non',
  cardFields: [
    'Observation',
    'Mécanisme compris',
    'Inconnue',
    'Choix historique',
    'Évolution',
    'Possibilité nouvelle',
    'Combinaison proposée',
    'Prédiction',
    'Expérience',
    'Résultat et erreur',
    'Conclusion et mémoire',
  ],
  toFill: 'à remplir une fois l’expérience menée',
  error: 'Erreur',
  statuses: { established: 'établi', hypothesis: 'hypothèse', novelty: 'nouveauté' },
  noveltyToVerify: 'nouveauté à vérifier',
  declared: 'déclaré',
  unchecked: 'non jugé par le gardien',
  serves: 'Sert',
  driftLog: 'Journal de dérive',
  driftBy: { guardian: 'hors de l’objectif', schema: 'refusé par le schéma' },
  noDrift: 'Aucun élément n’a quitté l’objectif.',
  sources: 'Sources',
  via: 'via',
  noResults: 'Aucun résultat n’a été obtenu.',
  statistics: 'Statistiques',
  stats: {
    runs: 'Exécutions',
    modelCalls: 'Appels au modèle',
    searches: 'Recherches',
    results: 'Résultats obtenus',
    items: 'Éléments',
    rejected: 'Éléments rejetés',
    downgraded: 'Statuts abaissés',
    noveltiesToVerify: 'Nouveautés à vérifier',
    redos: 'Passages refaits',
    loops: 'Passages rouverts',
  },
  capabilityQuestion:
    'Quel changement de principe rendrait possible quelque chose de difficile aujourd’hui, pas seulement plus rapide ?',
  capabilityAim:
    'Quel changement de principe rendrait possible ceci, difficile aujourd’hui : {capability} ?',
  capabilityAimed: 'Capacité visée',
  noCapabilityNamed: 'aucune nommée : l’étude propose des candidates',
  analoguesNamed: 'Ruptures à déconstruire',
  newCapability: 'Capacité nouvelle visée',
  improves: 'Ce qui s’améliore',
  forWhom: 'Pour qui',
  liftedConstraint: 'Contrainte levée',
  hardToday: 'Pourquoi c’est difficile aujourd’hui',
  principleChange: 'Changement de principe',
  principles: {
    representation: 'représentation',
    distribution: 'répartition du travail',
    responsibility: 'responsabilité',
    trust: 'confiance',
    verification: 'ce qui est vérifié',
    other: 'autre',
  },
  componentsAssembly: 'Composants → assemblage',
  assembly: 'assemblage',
  gives: 'apporte aux autres',
  capabilityOpened: 'Capacité ouverte',
  pattern: 'Motif d’assemblage',
  components: 'Composants',
  domain: 'Domaine',
  arrow: '→',
  architectureKinds: {
    capability: 'capacité nouvelle',
    improvement: 'amélioration : plus rapide ou moins cher',
  },
  judgedImprovement: 'le gardien l’a jugée seulement plus rapide ou moins chère',
  none: 'aucun',
};

const es: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'Si tuviéramos que satisfacer las necesidades de hoy con los conocimientos y las técnicas disponibles hoy, ¿cómo organizaríamos este objeto?',
  study: 'Estudio',
  charter: 'Carta',
  object: 'Objeto',
  question: 'Pregunta guía',
  objective: 'Objetivo',
  needs: 'Necesidades y criterios de hoy',
  leads: 'Pistas del usuario',
  leadsNote: 'ejemplos por verificar, no verdades',
  outOfScope: 'Fuera del alcance',
  charterHash: 'Huella de la carta (SHA-256)',
  amendments: 'Enmiendas',
  amendmentVerdicts: {
    refines: 'precisa el objetivo, aceptada',
    conflicts: 'contradice la carta',
    changesObjective: 'cambia el objetivo',
    unclassified: 'no se pudo clasificar',
  },
  refused: 'rechazada',
  notices: 'Antes de leer',
  noticeTexts: {
    analoguesNotDeconstructed: 'Rupturas no deconstruidas: {detail}.',
    noCapability: 'Ninguna arquitectura busca una nueva capacidad: el diseño solo ofrece mejoras.',
    noSources:
      'El estudio no tenía ninguna fuente de búsqueda: no se pudo establecer ninguna afirmación ni contrastar ninguna novedad con lo existente.',
    stopped: 'La ejecución se detuvo ({detail}); este dosier es parcial.',
    failed: 'La ejecución falló ({detail}); este dosier es parcial.',
    cancelled: 'La ejecución se canceló; este dosier es parcial.',
    passagesNotRun: 'Pasajes no ejecutados: {detail}.',
    uncheckedItems: 'Elementos que el guardián aún no juzgó, en: {detail}.',
    searchesSkipped: 'Se agotó el presupuesto de búsquedas: {detail}.',
    leadsNotVerified: 'Pistas sin veredicto: {detail}.',
    noveltiesToVerify: 'Novedades aún por contrastar con lo existente: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'límite de llamadas al modelo',
    timeoutMs: 'límite de tiempo',
    policy: 'política de presupuesto',
  },
  principle: 'El principio',
  principleText:
    'Observar el objeto, entrar en sus mecanismos, comprender sus componentes y sus interacciones. Encontrar los problemas a los que respondía su construcción, con los medios y los conocimientos de su época. Estudiar los avances ocurridos desde entonces, en su dominio y en los dominios vecinos. Usar esta comprensión para imaginar otra organización del sistema y diseñar los experimentos que la pondrían a prueba en su conjunto. Un conocimiento establecido cita un resultado obtenido durante este estudio; una hipótesis es plausible pero no está documentada aquí; una novedad se contrasta con lo existente.',
  passages: 'Los pasajes',
  passage: 'Pasaje',
  state: 'Estado',
  passageNames: {
    observe: 'Observar',
    decompose: 'Descomponer',
    historicalChoices: 'Comprender las decisiones de su época',
    changes: 'Examinar lo que cambió',
    cross: 'Cruzar pasado y presente',
    design: 'Diseñar varias organizaciones',
    confront: 'Confrontar',
  },
  passageStates: {
    complete: 'completo',
    partial: 'parcial',
    unchecked: 'no juzgado por el guardián',
    notRun: 'no ejecutado',
  },
  collections: {
    analogues: 'Rupturas por ensamblaje',
    capabilities: 'Nuevas capacidades candidatas',
    observations: 'Observaciones',
    pieces: 'Piezas y sus incógnitas',
    chain: 'La cadena completa',
    historicalChoices: 'Decisiones y sus condiciones',
    advances: 'Avances desde entonces',
    leadVerdicts: 'Pistas del usuario, verificadas',
    independentLeads: 'Pistas encontradas más allá',
    references: 'Mejores realizaciones actuales',
    constraints: 'Restricciones',
    revisableDecisions: 'Decisiones que se volvieron revisables',
    combinations: 'Combinaciones',
    architectures: 'Arquitecturas',
    threeStates: 'Tres estados',
    noveltyClaims: 'Lo que es nuevo y lo que no',
    experiments: 'Experimentos',
    cards: 'Fichas de mecanismo',
  },
  kinds: { behaviour: 'Comportamiento', use: 'Uso', variation: 'Variación', failure: 'Fallo' },
  conditions: 'Condiciones',
  era: 'Época',
  function: 'Función',
  inputs: 'Entradas',
  outputs: 'Salidas',
  relations: 'Relaciones',
  unknowns: 'Incógnitas',
  parent: 'Detalle de',
  pieces: 'Piezas',
  factors: 'Condiciones de la época',
  factorNames: {
    hardware: 'hardware',
    tools: 'herramientas',
    uses: 'usos',
    knowledge: 'conocimientos',
    costs: 'costes',
    compatibility: 'compatibilidad',
    other: 'otro',
  },
  date: 'Fecha',
  evidence: 'Prueba',
  availability: 'Disponibilidad',
  otherDomain: 'de otro dominio',
  verdicts: {
    relevant: 'pertinente',
    partlyRelevant: 'parcialmente pertinente',
    notRelevant: 'no pertinente',
  },
  unverifiedLead: 'sin veredicto',
  toolKinds: { mathematical: 'matemática', technical: 'técnica', other: 'otra' },
  constraintStates: {
    remains: 'Persisten',
    weakened: 'Se han atenuado',
    newRequirement: 'Nuevas exigencias',
  },
  because: 'Porque',
  opens: 'Abre',
  states: {
    atItsTime: 'El objeto en su época',
    currentBest: 'Mejores realizaciones actuales',
    proposal: 'Nuestra propuesta',
  },
  enables: 'Lo que A permite a B',
  exchange: 'Lo que intercambian',
  cost: 'Lo que cuesta',
  changes: 'Cambia',
  changeKinds: {
    representation: 'la representación',
    distribution: 'el reparto del trabajo',
    responsibilities: 'las responsabilidades',
  },
  designLeads: 'Pistas de diseño',
  mechanism: 'Mecanismo',
  benefit: 'Beneficio esperado',
  addedCost: 'Coste añadido',
  counterexample: 'Contraejemplo posible',
  chainCoverage: 'En toda la cadena',
  uncovered: 'Etapas no cubiertas',
  predictions: 'Predicciones',
  architecture: 'Arquitectura',
  priorArt: 'Lo existente',
  priorArtVerdicts: { novel: 'nuevo', partlyNovel: 'en parte nuevo', exists: 'ya existe' },
  decides: 'Decide entre',
  protocol: 'Protocolo',
  measures: 'Medidas',
  criteria: 'Criterios',
  expected: 'Resultados esperados',
  wholeChain: 'Pone a prueba toda la cadena',
  yes: 'sí',
  no: 'no',
  cardFields: [
    'Observación',
    'Mecanismo comprendido',
    'Incógnita',
    'Decisión histórica',
    'Evolución',
    'Posibilidad nueva',
    'Combinación propuesta',
    'Predicción',
    'Experimento',
    'Resultado y error',
    'Conclusión y memoria',
  ],
  toFill: 'por completar tras el experimento',
  error: 'Error',
  statuses: { established: 'establecido', hypothesis: 'hipótesis', novelty: 'novedad' },
  noveltyToVerify: 'novedad por verificar',
  declared: 'declarado',
  unchecked: 'no juzgado por el guardián',
  serves: 'Sirve',
  driftLog: 'Registro de desvíos',
  driftBy: { guardian: 'fuera del objetivo', schema: 'rechazado por el esquema' },
  noDrift: 'Ningún elemento se salió del objetivo.',
  sources: 'Fuentes',
  via: 'vía',
  noResults: 'No se obtuvo ningún resultado.',
  statistics: 'Estadísticas',
  stats: {
    runs: 'Ejecuciones',
    modelCalls: 'Llamadas al modelo',
    searches: 'Búsquedas',
    results: 'Resultados obtenidos',
    items: 'Elementos',
    rejected: 'Elementos rechazados',
    downgraded: 'Estados rebajados',
    noveltiesToVerify: 'Novedades por verificar',
    redos: 'Pasajes rehechos',
    loops: 'Pasajes reabiertos',
  },
  capabilityQuestion:
    '¿Qué cambio de principio haría posible algo difícil hoy, no solo más rápido?',
  capabilityAim: '¿Qué cambio de principio haría posible esto, difícil hoy: {capability}?',
  capabilityAimed: 'Capacidad buscada',
  noCapabilityNamed: 'ninguna nombrada: el estudio propone candidatas',
  analoguesNamed: 'Rupturas por deconstruir',
  newCapability: 'Nueva capacidad buscada',
  improves: 'Lo que mejora',
  forWhom: 'Para quién',
  liftedConstraint: 'Restricción levantada',
  hardToday: 'Por qué es difícil hoy',
  principleChange: 'Cambio de principio',
  principles: {
    representation: 'representación',
    distribution: 'reparto del trabajo',
    responsibility: 'responsabilidad',
    trust: 'confianza',
    verification: 'lo que se verifica',
    other: 'otro',
  },
  componentsAssembly: 'Componentes → ensamblaje',
  assembly: 'ensamblaje',
  gives: 'aporta a los demás',
  capabilityOpened: 'Capacidad abierta',
  pattern: 'Patrón de ensamblaje',
  components: 'Componentes',
  domain: 'Dominio',
  arrow: '→',
  architectureKinds: {
    capability: 'nueva capacidad',
    improvement: 'mejora: más rápido o más barato',
  },
  judgedImprovement: 'el guardián la juzgó solo más rápida o más barata',
  none: 'ninguno',
};

const de: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'Wenn wir die Bedürfnisse von heute mit dem Wissen und den Techniken von heute erfüllen müssten, wie würden wir diesen Gegenstand organisieren?',
  study: 'Studie',
  charter: 'Charta',
  object: 'Gegenstand',
  question: 'Leitfrage',
  objective: 'Ziel',
  needs: 'Bedürfnisse und Kriterien von heute',
  leads: 'Ansätze des Nutzers',
  leadsNote: 'Beispiele zum Prüfen, keine Wahrheiten',
  outOfScope: 'Außerhalb des Rahmens',
  charterHash: 'Prüfsumme der Charta (SHA-256)',
  amendments: 'Ergänzungen',
  amendmentVerdicts: {
    refines: 'präzisiert das Ziel, angenommen',
    conflicts: 'widerspricht der Charta',
    changesObjective: 'ändert das Ziel',
    unclassified: 'konnte nicht eingeordnet werden',
  },
  refused: 'abgelehnt',
  notices: 'Vor dem Lesen',
  noticeTexts: {
    analoguesNotDeconstructed: 'Nicht zerlegte Durchbrüche: {detail}.',
    noCapability:
      'Keine Architektur zielt auf eine neue Fähigkeit: Der Entwurf bietet nur Verbesserungen.',
    noSources:
      'Die Studie hatte keine Suchquelle: Keine Aussage konnte belegt und keine Neuheit mit dem Stand der Technik abgeglichen werden.',
    stopped: 'Der Lauf wurde angehalten ({detail}); dieses Dossier ist unvollständig.',
    failed: 'Der Lauf ist fehlgeschlagen ({detail}); dieses Dossier ist unvollständig.',
    cancelled: 'Der Lauf wurde abgebrochen; dieses Dossier ist unvollständig.',
    passagesNotRun: 'Nicht ausgeführte Schritte: {detail}.',
    uncheckedItems: 'Vom Wächter noch nicht beurteilte Einträge in: {detail}.',
    searchesSkipped: 'Das Suchbudget ist aufgebraucht: {detail}.',
    leadsNotVerified: 'Ansätze ohne Urteil: {detail}.',
    noveltiesToVerify: 'Noch mit dem Stand der Technik abzugleichende Neuheiten: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'Grenze der Modellaufrufe',
    timeoutMs: 'Zeitgrenze',
    policy: 'Budgetrichtlinie',
  },
  principle: 'Das Prinzip',
  principleText:
    'Den Gegenstand beobachten, in seine Mechanismen eindringen, seine Bauteile und ihr Zusammenwirken verstehen. Die Probleme wiederfinden, auf die seine Bauweise antwortete, mit den Mitteln und dem Wissen ihrer Zeit. Die seither erzielten Fortschritte untersuchen, im eigenen Gebiet und in benachbarten. Dieses Verständnis nutzen, um eine andere Organisation des Systems zu entwerfen, und die Experimente planen, die sie als Ganzes prüfen würden. Eine belegte Aussage zitiert ein in dieser Studie gefundenes Ergebnis; eine Hypothese ist plausibel, hier aber nicht belegt; eine Neuheit wird mit dem Stand der Technik abgeglichen.',
  passages: 'Die Schritte',
  passage: 'Schritt',
  state: 'Stand',
  passageNames: {
    observe: 'Beobachten',
    decompose: 'Zerlegen',
    historicalChoices: 'Die Entscheidungen ihrer Zeit verstehen',
    changes: 'Untersuchen, was sich geändert hat',
    cross: 'Vergangenheit und Gegenwart kreuzen',
    design: 'Mehrere Organisationen entwerfen',
    confront: 'Gegenüberstellen',
  },
  passageStates: {
    complete: 'abgeschlossen',
    partial: 'teilweise',
    unchecked: 'vom Wächter nicht beurteilt',
    notRun: 'nicht ausgeführt',
  },
  collections: {
    analogues: 'Durchbrüche durch Zusammenbau',
    capabilities: 'Kandidaten für neue Fähigkeiten',
    observations: 'Beobachtungen',
    pieces: 'Bauteile und ihre Unbekannten',
    chain: 'Die ganze Kette',
    historicalChoices: 'Entscheidungen und ihre Bedingungen',
    advances: 'Fortschritte seither',
    leadVerdicts: 'Ansätze des Nutzers, geprüft',
    independentLeads: 'Darüber hinaus gefundene Ansätze',
    references: 'Beste heutige Umsetzungen',
    constraints: 'Zwänge',
    revisableDecisions: 'Revidierbar gewordene Entscheidungen',
    combinations: 'Kombinationen',
    architectures: 'Architekturen',
    threeStates: 'Drei Zustände',
    noveltyClaims: 'Was neu ist und was nicht',
    experiments: 'Experimente',
    cards: 'Mechanismuskarten',
  },
  kinds: { behaviour: 'Verhalten', use: 'Nutzung', variation: 'Variante', failure: 'Ausfall' },
  conditions: 'Bedingungen',
  era: 'Zeit',
  function: 'Funktion',
  inputs: 'Eingaben',
  outputs: 'Ausgaben',
  relations: 'Beziehungen',
  unknowns: 'Unbekannte',
  parent: 'Detail von',
  pieces: 'Bauteile',
  factors: 'Bedingungen der Zeit',
  factorNames: {
    hardware: 'Hardware',
    tools: 'Werkzeuge',
    uses: 'Nutzungen',
    knowledge: 'Wissen',
    costs: 'Kosten',
    compatibility: 'Kompatibilität',
    other: 'Sonstiges',
  },
  date: 'Datum',
  evidence: 'Beleg',
  availability: 'Verfügbarkeit',
  otherDomain: 'aus einem anderen Gebiet',
  verdicts: {
    relevant: 'relevant',
    partlyRelevant: 'teilweise relevant',
    notRelevant: 'nicht relevant',
  },
  unverifiedLead: 'ohne Urteil',
  toolKinds: { mathematical: 'mathematisch', technical: 'technisch', other: 'sonstig' },
  constraintStates: {
    remains: 'Bestehen fort',
    weakened: 'Haben sich abgeschwächt',
    newRequirement: 'Neue Anforderungen',
  },
  because: 'Weil',
  opens: 'Eröffnet',
  states: {
    atItsTime: 'Der Gegenstand in seiner Zeit',
    currentBest: 'Beste heutige Umsetzungen',
    proposal: 'Unser Vorschlag',
  },
  enables: 'Was A für B ermöglicht',
  exchange: 'Was sie austauschen',
  cost: 'Was es kostet',
  changes: 'Ändert',
  changeKinds: {
    representation: 'die Darstellung',
    distribution: 'die Arbeitsteilung',
    responsibilities: 'die Zuständigkeiten',
  },
  designLeads: 'Entwurfsansätze',
  mechanism: 'Mechanismus',
  benefit: 'Erwarteter Nutzen',
  addedCost: 'Zusätzliche Kosten',
  counterexample: 'Mögliches Gegenbeispiel',
  chainCoverage: 'Über die ganze Kette',
  uncovered: 'Nicht abgedeckte Stufen',
  predictions: 'Vorhersagen',
  architecture: 'Architektur',
  priorArt: 'Stand der Technik',
  priorArtVerdicts: { novel: 'neu', partlyNovel: 'teilweise neu', exists: 'existiert bereits' },
  decides: 'Entscheidet zwischen',
  protocol: 'Protokoll',
  measures: 'Messgrößen',
  criteria: 'Kriterien',
  expected: 'Erwartete Ergebnisse',
  wholeChain: 'Prüft die ganze Kette',
  yes: 'ja',
  no: 'nein',
  cardFields: [
    'Beobachtung',
    'Verstandener Mechanismus',
    'Unbekannte',
    'Historische Entscheidung',
    'Entwicklung',
    'Neue Möglichkeit',
    'Vorgeschlagene Kombination',
    'Vorhersage',
    'Experiment',
    'Ergebnis und Fehler',
    'Schluss und Gedächtnis',
  ],
  toFill: 'nach dem Experiment auszufüllen',
  error: 'Fehler',
  statuses: { established: 'belegt', hypothesis: 'Hypothese', novelty: 'Neuheit' },
  noveltyToVerify: 'zu prüfende Neuheit',
  declared: 'angegeben',
  unchecked: 'vom Wächter nicht beurteilt',
  serves: 'Dient',
  driftLog: 'Abweichungsprotokoll',
  driftBy: { guardian: 'abseits des Ziels', schema: 'vom Schema abgelehnt' },
  noDrift: 'Kein Eintrag hat das Ziel verlassen.',
  sources: 'Quellen',
  via: 'über',
  noResults: 'Es wurde kein Ergebnis gefunden.',
  statistics: 'Statistik',
  stats: {
    runs: 'Läufe',
    modelCalls: 'Modellaufrufe',
    searches: 'Suchen',
    results: 'Gefundene Ergebnisse',
    items: 'Einträge',
    rejected: 'Abgelehnte Einträge',
    downgraded: 'Herabgestufte Status',
    noveltiesToVerify: 'Zu prüfende Neuheiten',
    redos: 'Wiederholte Schritte',
    loops: 'Wieder geöffnete Schritte',
  },
  capabilityQuestion:
    'Welche Änderung des Prinzips würde etwas möglich machen, das heute schwierig ist, nicht nur schneller?',
  capabilityAim:
    'Welche Änderung des Prinzips würde dies möglich machen, das heute schwierig ist: {capability}?',
  capabilityAimed: 'Angestrebte Fähigkeit',
  noCapabilityNamed: 'keine benannt: Die Studie schlägt Kandidaten vor',
  analoguesNamed: 'Zu zerlegende Durchbrüche',
  newCapability: 'Angestrebte neue Fähigkeit',
  improves: 'Was sich verbessert',
  forWhom: 'Für wen',
  liftedConstraint: 'Aufgehobene Beschränkung',
  hardToday: 'Warum es heute schwierig ist',
  principleChange: 'Änderung des Prinzips',
  principles: {
    representation: 'Darstellung',
    distribution: 'Arbeitsteilung',
    responsibility: 'Verantwortung',
    trust: 'Vertrauen',
    verification: 'was geprüft wird',
    other: 'Sonstiges',
  },
  componentsAssembly: 'Bausteine → Zusammenbau',
  assembly: 'Zusammenbau',
  gives: 'bringt den anderen',
  capabilityOpened: 'Eröffnete Fähigkeit',
  pattern: 'Muster des Zusammenbaus',
  components: 'Bausteine',
  domain: 'Gebiet',
  arrow: '→',
  architectureKinds: {
    capability: 'neue Fähigkeit',
    improvement: 'Verbesserung: schneller oder billiger',
  },
  judgedImprovement: 'der Wächter hat sie nur als schneller oder billiger beurteilt',
  none: 'keine',
};

// Brazilian Portuguese, as the documentation.
const pt: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'Se tivéssemos de satisfazer as necessidades de hoje com os conhecimentos e as técnicas disponíveis hoje, como organizaríamos este objeto?',
  study: 'Estudo',
  charter: 'Carta',
  object: 'Objeto',
  question: 'Pergunta orientadora',
  objective: 'Objetivo',
  needs: 'Necessidades e critérios de hoje',
  leads: 'Pistas do usuário',
  leadsNote: 'exemplos a verificar, não verdades',
  outOfScope: 'Fora do escopo',
  charterHash: 'Impressão da carta (SHA-256)',
  amendments: 'Emendas',
  amendmentVerdicts: {
    refines: 'precisa o objetivo, aceita',
    conflicts: 'contradiz a carta',
    changesObjective: 'muda o objetivo',
    unclassified: 'não pôde ser classificada',
  },
  refused: 'recusada',
  notices: 'Antes de ler',
  noticeTexts: {
    analoguesNotDeconstructed: 'Rupturas não desconstruídas: {detail}.',
    noCapability:
      'Nenhuma arquitetura visa uma nova capacidade: o projeto oferece apenas melhorias.',
    noSources:
      'O estudo não tinha nenhuma fonte de pesquisa: nenhuma afirmação pôde ser estabelecida, e nenhuma novidade confrontada com o existente.',
    stopped: 'A execução foi interrompida ({detail}); este dossiê é parcial.',
    failed: 'A execução falhou ({detail}); este dossiê é parcial.',
    cancelled: 'A execução foi cancelada; este dossiê é parcial.',
    passagesNotRun: 'Passagens não executadas: {detail}.',
    uncheckedItems: 'Itens que o guardião ainda não julgou, em: {detail}.',
    searchesSkipped: 'O orçamento de pesquisas se esgotou: {detail}.',
    leadsNotVerified: 'Pistas sem veredito: {detail}.',
    noveltiesToVerify: 'Novidades ainda a confrontar com o existente: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'limite de chamadas ao modelo',
    timeoutMs: 'limite de tempo',
    policy: 'política de orçamento',
  },
  principle: 'O princípio',
  principleText:
    'Observar o objeto, entrar em seus mecanismos, compreender seus componentes e suas interações. Reencontrar os problemas a que sua construção respondia, com os meios e os conhecimentos de sua época. Estudar os avanços ocorridos desde então, em seu domínio e nos domínios vizinhos. Usar essa compreensão para imaginar outra organização do sistema e conceber os experimentos que a poriam à prova em seu conjunto. Um conhecimento estabelecido cita um resultado obtido durante este estudo; uma hipótese é plausível, mas não está documentada aqui; uma novidade é confrontada com o existente.',
  passages: 'As passagens',
  passage: 'Passagem',
  state: 'Estado',
  passageNames: {
    observe: 'Observar',
    decompose: 'Decompor',
    historicalChoices: 'Compreender as escolhas da época',
    changes: 'Examinar o que mudou',
    cross: 'Cruzar passado e presente',
    design: 'Conceber várias organizações',
    confront: 'Confrontar',
  },
  passageStates: {
    complete: 'concluída',
    partial: 'parcial',
    unchecked: 'não julgada pelo guardião',
    notRun: 'não executada',
  },
  collections: {
    analogues: 'Rupturas por montagem',
    capabilities: 'Novas capacidades candidatas',
    observations: 'Observações',
    pieces: 'Peças e suas incógnitas',
    chain: 'A cadeia completa',
    historicalChoices: 'Escolhas e suas condições',
    advances: 'Avanços desde então',
    leadVerdicts: 'Pistas do usuário, verificadas',
    independentLeads: 'Pistas encontradas além delas',
    references: 'Melhores realizações atuais',
    constraints: 'Restrições',
    revisableDecisions: 'Decisões que se tornaram revisáveis',
    combinations: 'Combinações',
    architectures: 'Arquiteturas',
    threeStates: 'Três estados',
    noveltyClaims: 'O que é novo, e o que não é',
    experiments: 'Experimentos',
    cards: 'Fichas de mecanismo',
  },
  kinds: { behaviour: 'Comportamento', use: 'Uso', variation: 'Variação', failure: 'Falha' },
  conditions: 'Condições',
  era: 'Época',
  function: 'Função',
  inputs: 'Entradas',
  outputs: 'Saídas',
  relations: 'Relações',
  unknowns: 'Incógnitas',
  parent: 'Detalhe de',
  pieces: 'Peças',
  factors: 'Condições da época',
  factorNames: {
    hardware: 'hardware',
    tools: 'ferramentas',
    uses: 'usos',
    knowledge: 'conhecimentos',
    costs: 'custos',
    compatibility: 'compatibilidade',
    other: 'outro',
  },
  date: 'Data',
  evidence: 'Prova',
  availability: 'Disponibilidade',
  otherDomain: 'de outro domínio',
  verdicts: {
    relevant: 'pertinente',
    partlyRelevant: 'parcialmente pertinente',
    notRelevant: 'não pertinente',
  },
  unverifiedLead: 'sem veredito',
  toolKinds: { mathematical: 'matemática', technical: 'técnica', other: 'outra' },
  constraintStates: {
    remains: 'Persistem',
    weakened: 'Se atenuaram',
    newRequirement: 'Novas exigências',
  },
  because: 'Porque',
  opens: 'Abre',
  states: {
    atItsTime: 'O objeto em sua época',
    currentBest: 'Melhores realizações atuais',
    proposal: 'Nossa proposta',
  },
  enables: 'O que A permite a B',
  exchange: 'O que trocam',
  cost: 'O que custa',
  changes: 'Muda',
  changeKinds: {
    representation: 'a representação',
    distribution: 'a divisão do trabalho',
    responsibilities: 'as responsabilidades',
  },
  designLeads: 'Pistas de concepção',
  mechanism: 'Mecanismo',
  benefit: 'Benefício esperado',
  addedCost: 'Custo adicional',
  counterexample: 'Contraexemplo possível',
  chainCoverage: 'Em toda a cadeia',
  uncovered: 'Etapas não cobertas',
  predictions: 'Previsões',
  architecture: 'Arquitetura',
  priorArt: 'O existente',
  priorArtVerdicts: { novel: 'novo', partlyNovel: 'em parte novo', exists: 'já existe' },
  decides: 'Decide entre',
  protocol: 'Protocolo',
  measures: 'Medidas',
  criteria: 'Critérios',
  expected: 'Resultados esperados',
  wholeChain: 'Põe à prova toda a cadeia',
  yes: 'sim',
  no: 'não',
  cardFields: [
    'Observação',
    'Mecanismo compreendido',
    'Incógnita',
    'Escolha histórica',
    'Evolução',
    'Possibilidade nova',
    'Combinação proposta',
    'Previsão',
    'Experimento',
    'Resultado e erro',
    'Conclusão e memória',
  ],
  toFill: 'a preencher após o experimento',
  error: 'Erro',
  statuses: { established: 'estabelecido', hypothesis: 'hipótese', novelty: 'novidade' },
  noveltyToVerify: 'novidade a verificar',
  declared: 'declarado',
  unchecked: 'não julgado pelo guardião',
  serves: 'Serve',
  driftLog: 'Registro de desvios',
  driftBy: { guardian: 'fora do objetivo', schema: 'recusado pelo esquema' },
  noDrift: 'Nenhum item saiu do objetivo.',
  sources: 'Fontes',
  via: 'via',
  noResults: 'Nenhum resultado foi obtido.',
  statistics: 'Estatísticas',
  stats: {
    runs: 'Execuções',
    modelCalls: 'Chamadas ao modelo',
    searches: 'Pesquisas',
    results: 'Resultados obtidos',
    items: 'Itens',
    rejected: 'Itens rejeitados',
    downgraded: 'Estados rebaixados',
    noveltiesToVerify: 'Novidades a verificar',
    redos: 'Passagens refeitas',
    loops: 'Passagens reabertas',
  },
  capabilityQuestion:
    'Que mudança de princípio tornaria possível algo difícil hoje, e não apenas mais rápido?',
  capabilityAim: 'Que mudança de princípio tornaria isto possível, difícil hoje: {capability}?',
  capabilityAimed: 'Capacidade visada',
  noCapabilityNamed: 'nenhuma nomeada: o estudo propõe candidatas',
  analoguesNamed: 'Rupturas a desconstruir',
  newCapability: 'Nova capacidade visada',
  improves: 'O que melhora',
  forWhom: 'Para quem',
  liftedConstraint: 'Restrição removida',
  hardToday: 'Por que é difícil hoje',
  principleChange: 'Mudança de princípio',
  principles: {
    representation: 'representação',
    distribution: 'divisão do trabalho',
    responsibility: 'responsabilidade',
    trust: 'confiança',
    verification: 'o que é verificado',
    other: 'outro',
  },
  componentsAssembly: 'Componentes → montagem',
  assembly: 'montagem',
  gives: 'traz aos outros',
  capabilityOpened: 'Capacidade aberta',
  pattern: 'Padrão de montagem',
  components: 'Componentes',
  domain: 'Domínio',
  arrow: '→',
  architectureKinds: {
    capability: 'nova capacidade',
    improvement: 'melhoria: mais rápido ou mais barato',
  },
  judgedImprovement: 'o guardião a julgou apenas mais rápida ou mais barata',
  none: 'nenhum',
};

const ja: StudyLabels = {
  sep: '：',
  list: '、',
  guidingQuestion:
    '今日のニーズを今日の知識と技術で満たすとしたら、この対象をどのように組み立てるか？',
  study: '研究',
  charter: '憲章',
  object: '対象',
  question: '導きの問い',
  objective: '目的',
  needs: '今日のニーズと基準',
  leads: 'ユーザーの手がかり',
  leadsNote: '真実ではなく、検証すべき例',
  outOfScope: '範囲外',
  charterHash: '憲章のハッシュ（SHA-256）',
  amendments: '修正',
  amendmentVerdicts: {
    refines: '目的を具体化するため受理',
    conflicts: '憲章と矛盾',
    changesObjective: '目的を変更',
    unclassified: '分類できず',
  },
  refused: '却下',
  notices: '読む前に',
  noticeTexts: {
    analoguesNotDeconstructed: '分解されなかったブレークスルー：{detail}。',
    noCapability: '新しい能力を目指すアーキテクチャがありません。設計は改善だけです。',
    noSources:
      'この研究には検索ソースがありませんでした。どの主張も確立できず、どの新規性も先行事例と照合できませんでした。',
    stopped: '実行は停止しました（{detail}）。この資料は部分的です。',
    failed: '実行は失敗しました（{detail}）。この資料は部分的です。',
    cancelled: '実行は取り消されました。この資料は部分的です。',
    passagesNotRun: '実行されなかった段階：{detail}。',
    uncheckedItems: '守護者がまだ判定していない項目がある段階：{detail}。',
    searchesSkipped: '検索の予算が尽きました：{detail}。',
    leadsNotVerified: '判定のない手がかり：{detail}。',
    noveltiesToVerify: '先行事例との照合が残っている新規性：{detail}。',
  },
  stopReasons: {
    maxModelCalls: 'モデル呼び出しの上限',
    timeoutMs: '時間の上限',
    policy: '予算ポリシー',
  },
  principle: '原則',
  principleText:
    '対象を観察し、その仕組みに入り込み、部品とその相互作用を理解する。その構造が当時の手段と知識で応えていた問題を見つけ出す。それ以降に起きた進歩を、その分野と近い分野で調べる。この理解を使ってシステムの別の組み立てを構想し、それを全体として試す実験を設計する。確立した知識はこの研究中に取得した結果を引用する。仮説はもっともらしいが、ここでは裏付けがない。新規性は先行事例と照合される。',
  passages: '段階',
  passage: '段階',
  state: '状態',
  passageNames: {
    observe: '観察する',
    decompose: '分解する',
    historicalChoices: '当時の選択を理解する',
    changes: '変わったことを調べる',
    cross: '過去と現在を交差させる',
    design: '複数の組み立てを構想する',
    confront: '突き合わせる',
  },
  passageStates: {
    complete: '完了',
    partial: '部分的',
    unchecked: '守護者が未判定',
    notRun: '未実行',
  },
  collections: {
    analogues: '組み立てによるブレークスルー',
    capabilities: '新しい能力の候補',
    observations: '観察',
    pieces: '部品とその未知',
    chain: '全体の連鎖',
    historicalChoices: '選択とその条件',
    advances: 'それ以降の進歩',
    leadVerdicts: 'ユーザーの手がかりの検証',
    independentLeads: 'その先で見つけた手がかり',
    references: '現在の最良の実現',
    constraints: '制約',
    revisableDecisions: '見直し可能になった決定',
    combinations: '組み合わせ',
    architectures: 'アーキテクチャ',
    threeStates: '三つの状態',
    noveltyClaims: '新しいもの、そうでないもの',
    experiments: '実験',
    cards: '仕組みのカード',
  },
  kinds: { behaviour: '振る舞い', use: '使い方', variation: '変種', failure: '故障' },
  conditions: '条件',
  era: '時代',
  function: '機能',
  inputs: '入力',
  outputs: '出力',
  relations: '関係',
  unknowns: '未知',
  parent: '詳細の対象',
  pieces: '部品',
  factors: '当時の条件',
  factorNames: {
    hardware: 'ハードウェア',
    tools: '道具',
    uses: '使い方',
    knowledge: '知識',
    costs: 'コスト',
    compatibility: '互換性',
    other: 'その他',
  },
  date: '日付',
  evidence: '根拠',
  availability: '入手性',
  otherDomain: '他の分野から',
  verdicts: { relevant: '関連あり', partlyRelevant: '一部関連あり', notRelevant: '関連なし' },
  unverifiedLead: '判定なし',
  toolKinds: { mathematical: '数学的', technical: '技術的', other: 'その他' },
  constraintStates: { remains: '残っている', weakened: '弱まった', newRequirement: '新しい要件' },
  because: '理由',
  opens: '開く可能性',
  states: {
    atItsTime: '当時の対象',
    currentBest: '現在の最良の実現',
    proposal: '私たちの提案',
  },
  enables: 'A が B に可能にすること',
  exchange: '交換するもの',
  cost: 'かかるコスト',
  changes: '変えるもの',
  changeKinds: { representation: '表現', distribution: '作業の分担', responsibilities: '責任' },
  designLeads: '設計の方向',
  mechanism: '仕組み',
  benefit: '期待される利点',
  addedCost: '追加コスト',
  counterexample: '考えられる反例',
  chainCoverage: '連鎖全体での扱い',
  uncovered: 'カバーされない段',
  predictions: '予測',
  architecture: 'アーキテクチャ',
  priorArt: '先行事例',
  priorArtVerdicts: { novel: '新規', partlyNovel: '一部新規', exists: '既に存在' },
  decides: '比較する対象',
  protocol: '手順',
  measures: '測定',
  criteria: '基準',
  expected: '期待される結果',
  wholeChain: '連鎖全体を試す',
  yes: 'はい',
  no: 'いいえ',
  cardFields: [
    '観察',
    '理解した仕組み',
    '未知',
    '歴史的選択',
    '進化',
    '新しい可能性',
    '提案する組み合わせ',
    '予測',
    '実験',
    '結果と誤り',
    '結論と記憶',
  ],
  toFill: '実験の後に記入',
  error: '誤り',
  statuses: { established: '確立', hypothesis: '仮説', novelty: '新規性' },
  noveltyToVerify: '要検証の新規性',
  declared: '申告',
  unchecked: '守護者が未判定',
  serves: '役立つ点',
  driftLog: '逸脱の記録',
  driftBy: { guardian: '目的から外れた', schema: 'スキーマが拒否' },
  noDrift: '目的から外れた項目はありません。',
  sources: '情報源',
  via: '経由',
  noResults: '結果は取得されませんでした。',
  statistics: '統計',
  stats: {
    runs: '実行',
    modelCalls: 'モデル呼び出し',
    searches: '検索',
    results: '取得した結果',
    items: '項目',
    rejected: '却下された項目',
    downgraded: '引き下げた状態',
    noveltiesToVerify: '要検証の新規性',
    redos: 'やり直した段階',
    loops: '再び開いた段階',
  },
  capabilityQuestion:
    'どのような原理の変更が、単に速くするだけでなく、今日難しいことを可能にするか？',
  capabilityAim: 'どのような原理の変更が、今日難しいこれを可能にするか：{capability}？',
  capabilityAimed: '目指す能力',
  noCapabilityNamed: '指定なし：研究が候補を提案する',
  analoguesNamed: '分解するブレークスルー',
  newCapability: '目指す新しい能力',
  improves: '改善されるもの',
  forWhom: '誰のために',
  liftedConstraint: '取り除かれる制約',
  hardToday: '今日難しい理由',
  principleChange: '原理の変更',
  principles: {
    representation: '表現',
    distribution: '作業の分担',
    responsibility: '責任',
    trust: '信頼',
    verification: '検証の対象',
    other: 'その他',
  },
  componentsAssembly: '構成要素 → 組み立て',
  assembly: '組み立て',
  gives: '他にもたらすもの',
  capabilityOpened: '開かれた能力',
  pattern: '組み立てのパターン',
  components: '構成要素',
  domain: '分野',
  arrow: '→',
  architectureKinds: { capability: '新しい能力', improvement: '改善：より速いか安いだけ' },
  judgedImprovement: '守護者はより速いか安いだけと判定した',
  none: 'なし',
};

const zh: StudyLabels = {
  sep: '：',
  list: '；',
  guidingQuestion: '如果要用今天可用的知识和技术来满足今天的需求，我们会如何组织这个对象？',
  study: '研究',
  charter: '章程',
  object: '对象',
  question: '指导问题',
  objective: '目标',
  needs: '今天的需求与标准',
  leads: '用户的线索',
  leadsNote: '有待验证的例子，而非真理',
  outOfScope: '范围之外',
  charterHash: '章程哈希（SHA-256）',
  amendments: '修订',
  amendmentVerdicts: {
    refines: '细化目标，已接受',
    conflicts: '与章程冲突',
    changesObjective: '改变目标',
    unclassified: '无法分类',
  },
  refused: '已拒绝',
  notices: '阅读之前',
  noticeTexts: {
    analoguesNotDeconstructed: '未拆解的突破：{detail}。',
    noCapability: '没有架构以新能力为目标：设计只提供了改进。',
    noSources: '本研究没有检索来源：任何论断都无法确立，任何新颖性都无法与已有工作比对。',
    stopped: '运行已停止（{detail}）；本档案不完整。',
    failed: '运行失败（{detail}）；本档案不完整。',
    cancelled: '运行已取消；本档案不完整。',
    passagesNotRun: '未运行的环节：{detail}。',
    uncheckedItems: '守护者尚未判断的条目所在环节：{detail}。',
    searchesSkipped: '检索预算已用完：{detail}。',
    leadsNotVerified: '没有结论的线索：{detail}。',
    noveltiesToVerify: '仍待与已有工作比对的新颖性：{detail}。',
  },
  stopReasons: { maxModelCalls: '模型调用上限', timeoutMs: '时间上限', policy: '预算策略' },
  principle: '原则',
  principleText:
    '观察对象，深入其机制，理解其部件及其相互作用。找回其构造当年所回应的问题，以及当时的手段与知识。研究此后在其领域和相邻领域出现的进展。利用这些理解来设想系统的另一种组织方式，并设计能整体检验它的实验。已确立的知识引用本研究中检索到的结果；假设看似合理，但在此没有文献支持；新颖性要与已有工作比对。',
  passages: '环节',
  passage: '环节',
  state: '状态',
  passageNames: {
    observe: '观察',
    decompose: '分解',
    historicalChoices: '理解当年的选择',
    changes: '考察变化',
    cross: '交叉过去与现在',
    design: '设计多种组织方式',
    confront: '对照检验',
  },
  passageStates: {
    complete: '已完成',
    partial: '部分完成',
    unchecked: '守护者未判断',
    notRun: '未运行',
  },
  collections: {
    analogues: '由组装带来的突破',
    capabilities: '候选新能力',
    observations: '观察',
    pieces: '部件及其未知',
    chain: '完整链条',
    historicalChoices: '选择及其条件',
    advances: '此后的进展',
    leadVerdicts: '用户线索的验证',
    independentLeads: '另外找到的线索',
    references: '当前最佳实现',
    constraints: '约束',
    revisableDecisions: '变得可以修改的决定',
    combinations: '组合',
    architectures: '架构',
    threeStates: '三种状态',
    noveltyClaims: '哪些是新的，哪些不是',
    experiments: '实验',
    cards: '机制卡片',
  },
  kinds: { behaviour: '行为', use: '用途', variation: '变体', failure: '故障' },
  conditions: '条件',
  era: '时代',
  function: '功能',
  inputs: '输入',
  outputs: '输出',
  relations: '关系',
  unknowns: '未知',
  parent: '细化自',
  pieces: '部件',
  factors: '当年的条件',
  factorNames: {
    hardware: '硬件',
    tools: '工具',
    uses: '用途',
    knowledge: '知识',
    costs: '成本',
    compatibility: '兼容性',
    other: '其他',
  },
  date: '日期',
  evidence: '证据',
  availability: '可用性',
  otherDomain: '来自其他领域',
  verdicts: { relevant: '相关', partlyRelevant: '部分相关', notRelevant: '不相关' },
  unverifiedLead: '无结论',
  toolKinds: { mathematical: '数学', technical: '技术', other: '其他' },
  constraintStates: { remains: '仍然存在', weakened: '已经减弱', newRequirement: '新的要求' },
  because: '原因',
  opens: '带来的可能',
  states: { atItsTime: '当年的对象', currentBest: '当前最佳实现', proposal: '我们的提议' },
  enables: 'A 让 B 能做什么',
  exchange: '交换什么',
  cost: '代价',
  changes: '改变',
  changeKinds: { representation: '表示方式', distribution: '工作分配', responsibilities: '职责' },
  designLeads: '设计方向',
  mechanism: '机制',
  benefit: '预期收益',
  addedCost: '额外成本',
  counterexample: '可能的反例',
  chainCoverage: '覆盖整个链条',
  uncovered: '未覆盖的阶段',
  predictions: '预测',
  architecture: '架构',
  priorArt: '已有工作',
  priorArtVerdicts: { novel: '新颖', partlyNovel: '部分新颖', exists: '已经存在' },
  decides: '区分',
  protocol: '方案',
  measures: '测量',
  criteria: '标准',
  expected: '预期结果',
  wholeChain: '检验整个链条',
  yes: '是',
  no: '否',
  cardFields: [
    '观察',
    '理解的机制',
    '未知',
    '历史选择',
    '演变',
    '新的可能',
    '提议的组合',
    '预测',
    '实验',
    '结果与误差',
    '结论与记忆',
  ],
  toFill: '实验后填写',
  error: '误差',
  statuses: { established: '已确立', hypothesis: '假设', novelty: '新颖' },
  noveltyToVerify: '待验证的新颖性',
  declared: '声称',
  unchecked: '守护者未判断',
  serves: '服务于',
  driftLog: '偏离记录',
  driftBy: { guardian: '偏离目标', schema: '被模式拒绝' },
  noDrift: '没有条目偏离目标。',
  sources: '来源',
  via: '经由',
  noResults: '没有检索到结果。',
  statistics: '统计',
  stats: {
    runs: '运行',
    modelCalls: '模型调用',
    searches: '检索',
    results: '检索到的结果',
    items: '条目',
    rejected: '被拒绝的条目',
    downgraded: '被降低的状态',
    noveltiesToVerify: '待验证的新颖性',
    redos: '重做的环节',
    loops: '重新打开的环节',
  },
  capabilityQuestion: '什么样的原理变化能让今天难以做到的事成为可能，而不只是更快？',
  capabilityAim: '什么样的原理变化能让这件今天难以做到的事成为可能：{capability}？',
  capabilityAimed: '目标能力',
  noCapabilityNamed: '未指定：由研究提出候选',
  analoguesNamed: '待拆解的突破',
  newCapability: '目标新能力',
  improves: '改进的内容',
  forWhom: '为谁',
  liftedConstraint: '解除的约束',
  hardToday: '为何今天难以做到',
  principleChange: '原理的变化',
  principles: {
    representation: '表示方式',
    distribution: '工作分配',
    responsibility: '职责',
    trust: '信任',
    verification: '验证的对象',
    other: '其他',
  },
  componentsAssembly: '组件 → 组装',
  assembly: '组装',
  gives: '为其他组件带来',
  capabilityOpened: '开启的能力',
  pattern: '组装模式',
  components: '组件',
  domain: '领域',
  arrow: '→',
  architectureKinds: { capability: '新能力', improvement: '改进：更快或更便宜' },
  judgedImprovement: '守护者判定它只是更快或更便宜',
  none: '无',
};

const ko: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    '오늘의 요구를 오늘 사용할 수 있는 지식과 기술로 충족해야 한다면, 이 대상을 어떻게 구성하겠는가?',
  study: '연구',
  charter: '헌장',
  object: '대상',
  question: '길잡이 질문',
  objective: '목표',
  needs: '오늘의 요구와 기준',
  leads: '사용자의 단서',
  leadsNote: '진리가 아니라 검증할 예시',
  outOfScope: '범위 밖',
  charterHash: '헌장 해시 (SHA-256)',
  amendments: '수정안',
  amendmentVerdicts: {
    refines: '목표를 구체화함, 수락',
    conflicts: '헌장과 충돌',
    changesObjective: '목표를 바꿈',
    unclassified: '분류할 수 없음',
  },
  refused: '거부됨',
  notices: '읽기 전에',
  noticeTexts: {
    analoguesNotDeconstructed: '분해되지 않은 돌파구: {detail}.',
    noCapability: '새로운 능력을 목표로 하는 아키텍처가 없습니다. 설계는 개선만 제공합니다.',
    noSources:
      '이 연구에는 검색 소스가 없었습니다. 어떤 주장도 확립할 수 없었고, 어떤 새로움도 선행 사례와 대조할 수 없었습니다.',
    stopped: '실행이 중지되었습니다 ({detail}). 이 자료는 부분적입니다.',
    failed: '실행이 실패했습니다 ({detail}). 이 자료는 부분적입니다.',
    cancelled: '실행이 취소되었습니다. 이 자료는 부분적입니다.',
    passagesNotRun: '실행되지 않은 단계: {detail}.',
    uncheckedItems: '수호자가 아직 판단하지 않은 항목이 있는 단계: {detail}.',
    searchesSkipped: '검색 예산이 소진되었습니다: {detail}.',
    leadsNotVerified: '판정이 없는 단서: {detail}.',
    noveltiesToVerify: '아직 선행 사례와 대조해야 할 새로움: {detail}.',
  },
  stopReasons: { maxModelCalls: '모델 호출 한도', timeoutMs: '시간 한도', policy: '예산 정책' },
  principle: '원칙',
  principleText:
    '대상을 관찰하고, 그 메커니즘에 들어가, 구성 요소와 그 상호작용을 이해한다. 그 구조가 당대의 수단과 지식으로 답하던 문제를 되찾는다. 그 이후 그 분야와 인접 분야에서 일어난 진보를 연구한다. 이 이해를 바탕으로 시스템의 다른 구성을 상상하고, 그것을 전체로서 시험할 실험을 설계한다. 확립된 지식은 이 연구 중에 얻은 결과를 인용하고, 가설은 그럴듯하지만 여기서 문서로 뒷받침되지 않으며, 새로움은 선행 사례와 대조된다.',
  passages: '단계',
  passage: '단계',
  state: '상태',
  passageNames: {
    observe: '관찰하기',
    decompose: '분해하기',
    historicalChoices: '당대의 선택 이해하기',
    changes: '변한 것 살피기',
    cross: '과거와 현재 교차하기',
    design: '여러 구성 설계하기',
    confront: '대조하기',
  },
  passageStates: {
    complete: '완료',
    partial: '부분',
    unchecked: '수호자 미판단',
    notRun: '미실행',
  },
  collections: {
    analogues: '조립에 의한 돌파구',
    capabilities: '새로운 능력 후보',
    observations: '관찰',
    pieces: '부품과 그 미지',
    chain: '전체 사슬',
    historicalChoices: '선택과 그 조건',
    advances: '그 이후의 진보',
    leadVerdicts: '검증한 사용자의 단서',
    independentLeads: '그 너머에서 찾은 단서',
    references: '현재 최고의 구현',
    constraints: '제약',
    revisableDecisions: '다시 검토할 수 있게 된 결정',
    combinations: '조합',
    architectures: '아키텍처',
    threeStates: '세 가지 상태',
    noveltyClaims: '새로운 것과 그렇지 않은 것',
    experiments: '실험',
    cards: '메커니즘 카드',
  },
  kinds: { behaviour: '동작', use: '사용', variation: '변형', failure: '고장' },
  conditions: '조건',
  era: '시대',
  function: '기능',
  inputs: '입력',
  outputs: '출력',
  relations: '관계',
  unknowns: '미지',
  parent: '상위 부품',
  pieces: '부품',
  factors: '당대의 조건',
  factorNames: {
    hardware: '하드웨어',
    tools: '도구',
    uses: '사용',
    knowledge: '지식',
    costs: '비용',
    compatibility: '호환성',
    other: '기타',
  },
  date: '날짜',
  evidence: '근거',
  availability: '가용성',
  otherDomain: '다른 분야에서',
  verdicts: {
    relevant: '관련 있음',
    partlyRelevant: '부분적으로 관련 있음',
    notRelevant: '관련 없음',
  },
  unverifiedLead: '판정 없음',
  toolKinds: { mathematical: '수학적', technical: '기술적', other: '기타' },
  constraintStates: { remains: '남아 있음', weakened: '약해짐', newRequirement: '새로운 요구' },
  because: '이유',
  opens: '여는 가능성',
  states: { atItsTime: '당대의 대상', currentBest: '현재 최고의 구현', proposal: '우리의 제안' },
  enables: 'A가 B에게 가능하게 하는 것',
  exchange: '주고받는 것',
  cost: '드는 비용',
  changes: '바꾸는 것',
  changeKinds: { representation: '표현', distribution: '작업 분담', responsibilities: '책임' },
  designLeads: '설계 방향',
  mechanism: '메커니즘',
  benefit: '기대 효과',
  addedCost: '추가 비용',
  counterexample: '가능한 반례',
  chainCoverage: '전체 사슬에서',
  uncovered: '다루지 않은 단계',
  predictions: '예측',
  architecture: '아키텍처',
  priorArt: '선행 사례',
  priorArtVerdicts: { novel: '새로움', partlyNovel: '부분적으로 새로움', exists: '이미 있음' },
  decides: '비교 대상',
  protocol: '절차',
  measures: '측정',
  criteria: '기준',
  expected: '기대 결과',
  wholeChain: '전체 사슬을 시험함',
  yes: '예',
  no: '아니요',
  cardFields: [
    '관찰',
    '이해한 메커니즘',
    '미지',
    '역사적 선택',
    '변화',
    '새로운 가능성',
    '제안한 조합',
    '예측',
    '실험',
    '결과와 오류',
    '결론과 기억',
  ],
  toFill: '실험 후 작성',
  error: '오류',
  statuses: { established: '확립됨', hypothesis: '가설', novelty: '새로움' },
  noveltyToVerify: '검증할 새로움',
  declared: '선언',
  unchecked: '수호자 미판단',
  serves: '기여',
  driftLog: '이탈 기록',
  driftBy: { guardian: '목표에서 벗어남', schema: '스키마가 거부함' },
  noDrift: '목표에서 벗어난 항목이 없습니다.',
  sources: '출처',
  via: '경유',
  noResults: '얻은 결과가 없습니다.',
  statistics: '통계',
  stats: {
    runs: '실행',
    modelCalls: '모델 호출',
    searches: '검색',
    results: '얻은 결과',
    items: '항목',
    rejected: '거부된 항목',
    downgraded: '낮춘 상태',
    noveltiesToVerify: '검증할 새로움',
    redos: '다시 한 단계',
    loops: '다시 연 단계',
  },
  capabilityQuestion: '어떤 원리의 변화가 단지 더 빠르게가 아니라 오늘 어려운 일을 가능하게 할까?',
  capabilityAim: '어떤 원리의 변화가 오늘 어려운 이것을 가능하게 할까: {capability}?',
  capabilityAimed: '목표 능력',
  noCapabilityNamed: '지정 없음: 연구가 후보를 제안함',
  analoguesNamed: '분해할 돌파구',
  newCapability: '목표로 하는 새로운 능력',
  improves: '개선되는 것',
  forWhom: '누구를 위해',
  liftedConstraint: '해제되는 제약',
  hardToday: '오늘 어려운 이유',
  principleChange: '원리의 변화',
  principles: {
    representation: '표현',
    distribution: '작업 분담',
    responsibility: '책임',
    trust: '신뢰',
    verification: '검증 대상',
    other: '기타',
  },
  componentsAssembly: '구성 요소 → 조립',
  assembly: '조립',
  gives: '다른 요소에 주는 것',
  capabilityOpened: '열린 능력',
  pattern: '조립 패턴',
  components: '구성 요소',
  domain: '분야',
  arrow: '→',
  architectureKinds: { capability: '새로운 능력', improvement: '개선: 더 빠르거나 더 저렴함' },
  judgedImprovement: '수호자가 더 빠르거나 더 저렴할 뿐이라고 판단함',
  none: '없음',
};

const ru: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'Если бы нам нужно было удовлетворить сегодняшние потребности знаниями и технологиями, доступными сегодня, как бы мы устроили этот объект?',
  study: 'Исследование',
  charter: 'Хартия',
  object: 'Объект',
  question: 'Направляющий вопрос',
  objective: 'Цель',
  needs: 'Потребности и критерии сегодняшнего дня',
  leads: 'Идеи пользователя',
  leadsNote: 'примеры для проверки, а не истины',
  outOfScope: 'Вне рамок',
  charterHash: 'Хеш хартии (SHA-256)',
  amendments: 'Поправки',
  amendmentVerdicts: {
    refines: 'уточняет цель, принята',
    conflicts: 'противоречит хартии',
    changesObjective: 'меняет цель',
    unclassified: 'не удалось классифицировать',
  },
  refused: 'отклонена',
  notices: 'Перед чтением',
  noticeTexts: {
    analoguesNotDeconstructed: 'Неразобранные прорывы: {detail}.',
    noCapability:
      'Ни одна архитектура не нацелена на новую возможность: проект предлагает только улучшения.',
    noSources:
      'У исследования не было источника поиска: ни одно утверждение не удалось обосновать, ни одну новизну не удалось сверить с существующими работами.',
    stopped: 'Запуск остановлен ({detail}); досье неполное.',
    failed: 'Запуск завершился ошибкой ({detail}); досье неполное.',
    cancelled: 'Запуск отменён; досье неполное.',
    passagesNotRun: 'Невыполненные этапы: {detail}.',
    uncheckedItems: 'Элементы, ещё не оценённые стражем, в этапах: {detail}.',
    searchesSkipped: 'Бюджет поиска исчерпан: {detail}.',
    leadsNotVerified: 'Идеи без вердикта: {detail}.',
    noveltiesToVerify: 'Новизна, ещё не сверенная с существующими работами: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'лимит вызовов модели',
    timeoutMs: 'лимит времени',
    policy: 'бюджетная политика',
  },
  principle: 'Принцип',
  principleText:
    'Наблюдать объект, проникать в его механизмы, понимать его части и их взаимодействие. Найти задачи, на которые отвечало его устройство, со средствами и знаниями своего времени. Изучить достижения, появившиеся с тех пор, в его области и в соседних. Использовать это понимание, чтобы представить другую организацию системы, и спроектировать эксперименты, которые проверили бы её целиком. Установленное знание ссылается на результат, найденный в ходе этого исследования; гипотеза правдоподобна, но здесь не подтверждена документом; новизна сверяется с существующими работами.',
  passages: 'Этапы',
  passage: 'Этап',
  state: 'Состояние',
  passageNames: {
    observe: 'Наблюдать',
    decompose: 'Разбирать',
    historicalChoices: 'Понять решения своего времени',
    changes: 'Изучить, что изменилось',
    cross: 'Сопоставить прошлое и настоящее',
    design: 'Спроектировать несколько организаций',
    confront: 'Проверить',
  },
  passageStates: {
    complete: 'завершён',
    partial: 'частично',
    unchecked: 'не оценён стражем',
    notRun: 'не выполнен',
  },
  collections: {
    analogues: 'Прорывы через сборку',
    capabilities: 'Кандидаты в новые возможности',
    observations: 'Наблюдения',
    pieces: 'Части и их неизвестные',
    chain: 'Вся цепочка',
    historicalChoices: 'Решения и их условия',
    advances: 'Достижения с тех пор',
    leadVerdicts: 'Проверенные идеи пользователя',
    independentLeads: 'Идеи, найденные помимо них',
    references: 'Лучшие современные реализации',
    constraints: 'Ограничения',
    revisableDecisions: 'Решения, которые можно пересмотреть',
    combinations: 'Сочетания',
    architectures: 'Архитектуры',
    threeStates: 'Три состояния',
    noveltyClaims: 'Что ново, а что нет',
    experiments: 'Эксперименты',
    cards: 'Карточки механизмов',
  },
  kinds: {
    behaviour: 'Поведение',
    use: 'Использование',
    variation: 'Вариант',
    failure: 'Сбой',
  },
  conditions: 'Условия',
  era: 'Эпоха',
  function: 'Функция',
  inputs: 'Входы',
  outputs: 'Выходы',
  relations: 'Связи',
  unknowns: 'Неизвестные',
  parent: 'Уточняет',
  pieces: 'Части',
  factors: 'Условия времени',
  factorNames: {
    hardware: 'оборудование',
    tools: 'инструменты',
    uses: 'использование',
    knowledge: 'знания',
    costs: 'затраты',
    compatibility: 'совместимость',
    other: 'другое',
  },
  date: 'Дата',
  evidence: 'Доказательство',
  availability: 'Доступность',
  otherDomain: 'из другой области',
  verdicts: {
    relevant: 'уместна',
    partlyRelevant: 'частично уместна',
    notRelevant: 'неуместна',
  },
  unverifiedLead: 'без вердикта',
  toolKinds: { mathematical: 'математический', technical: 'технический', other: 'другой' },
  constraintStates: {
    remains: 'Сохраняются',
    weakened: 'Ослабли',
    newRequirement: 'Новые требования',
  },
  because: 'Потому что',
  opens: 'Открывает',
  states: {
    atItsTime: 'Объект в своё время',
    currentBest: 'Лучшие современные реализации',
    proposal: 'Наше предложение',
  },
  enables: 'Что A даёт B',
  exchange: 'Чем они обмениваются',
  cost: 'Чего это стоит',
  changes: 'Меняет',
  changeKinds: {
    representation: 'представление',
    distribution: 'распределение работы',
    responsibilities: 'обязанности',
  },
  designLeads: 'Направления проектирования',
  mechanism: 'Механизм',
  benefit: 'Ожидаемая польза',
  addedCost: 'Дополнительные затраты',
  counterexample: 'Возможный контрпример',
  chainCoverage: 'По всей цепочке',
  uncovered: 'Непокрытые звенья',
  predictions: 'Прогнозы',
  architecture: 'Архитектура',
  priorArt: 'Существующие работы',
  priorArtVerdicts: { novel: 'ново', partlyNovel: 'отчасти ново', exists: 'уже существует' },
  decides: 'Выбирает между',
  protocol: 'Протокол',
  measures: 'Измерения',
  criteria: 'Критерии',
  expected: 'Ожидаемые результаты',
  wholeChain: 'Проверяет всю цепочку',
  yes: 'да',
  no: 'нет',
  cardFields: [
    'Наблюдение',
    'Понятый механизм',
    'Неизвестное',
    'Историческое решение',
    'Эволюция',
    'Новая возможность',
    'Предлагаемое сочетание',
    'Прогноз',
    'Эксперимент',
    'Результат и ошибка',
    'Вывод и память',
  ],
  toFill: 'заполнить после эксперимента',
  error: 'Ошибка',
  statuses: { established: 'установлено', hypothesis: 'гипотеза', novelty: 'новизна' },
  noveltyToVerify: 'новизна для проверки',
  declared: 'заявлено',
  unchecked: 'не оценено стражем',
  serves: 'Служит',
  driftLog: 'Журнал отклонений',
  driftBy: { guardian: 'вне цели', schema: 'отклонено схемой' },
  noDrift: 'Ни один элемент не отклонился от цели.',
  sources: 'Источники',
  via: 'через',
  noResults: 'Результатов не найдено.',
  statistics: 'Статистика',
  stats: {
    runs: 'Запуски',
    modelCalls: 'Вызовы модели',
    searches: 'Поиски',
    results: 'Найденные результаты',
    items: 'Элементы',
    rejected: 'Отклонённые элементы',
    downgraded: 'Пониженные статусы',
    noveltiesToVerify: 'Новизна для проверки',
    redos: 'Переделанные этапы',
    loops: 'Вновь открытые этапы',
  },
  capabilityQuestion:
    'Какое изменение принципа сделало бы возможным то, что сегодня трудно, а не просто ускорило бы?',
  capabilityAim:
    'Какое изменение принципа сделало бы возможным то, что сегодня трудно: {capability}?',
  capabilityAimed: 'Искомая возможность',
  noCapabilityNamed: 'не названа: исследование предлагает кандидатов',
  analoguesNamed: 'Прорывы для разбора',
  newCapability: 'Искомая новая возможность',
  improves: 'Что улучшается',
  forWhom: 'Для кого',
  liftedConstraint: 'Снятое ограничение',
  hardToday: 'Почему это трудно сегодня',
  principleChange: 'Изменение принципа',
  principles: {
    representation: 'представление',
    distribution: 'распределение работы',
    responsibility: 'ответственность',
    trust: 'доверие',
    verification: 'что проверяется',
    other: 'другое',
  },
  componentsAssembly: 'Компоненты → сборка',
  assembly: 'сборка',
  gives: 'даёт остальным',
  capabilityOpened: 'Открытая возможность',
  pattern: 'Схема сборки',
  components: 'Компоненты',
  domain: 'Область',
  arrow: '→',
  architectureKinds: {
    capability: 'новая возможность',
    improvement: 'улучшение: быстрее или дешевле',
  },
  judgedImprovement: 'страж счёл её лишь более быстрой или дешёвой',
  none: 'нет',
};

const ar: StudyLabels = {
  sep: ': ',
  list: '؛ ',
  guidingQuestion:
    'لو كان علينا تلبية احتياجات اليوم بالمعارف والتقنيات المتاحة اليوم، فكيف كنا سننظّم هذا الشيء؟',
  study: 'دراسة',
  charter: 'الميثاق',
  object: 'الموضوع',
  question: 'السؤال الموجّه',
  objective: 'الهدف',
  needs: 'احتياجات اليوم ومعاييره',
  leads: 'مسارات المستخدم',
  leadsNote: 'أمثلة يجب التحقق منها، لا حقائق',
  outOfScope: 'خارج النطاق',
  charterHash: 'بصمة الميثاق (SHA-256)',
  amendments: 'التعديلات',
  amendmentVerdicts: {
    refines: 'يدقّق الهدف، مقبول',
    conflicts: 'يتعارض مع الميثاق',
    changesObjective: 'يغيّر الهدف',
    unclassified: 'تعذّر تصنيفه',
  },
  refused: 'مرفوض',
  notices: 'قبل القراءة',
  noticeTexts: {
    analoguesNotDeconstructed: 'اختراقات لم تُفكَّك: {detail}.',
    noCapability: 'لا تستهدف أي بنية قدرة جديدة: التصميم لا يقدّم سوى تحسينات.',
    noSources:
      'لم يكن للدراسة أي مصدر بحث: لم يمكن إثبات أي ادعاء، ولا مقارنة أي جِدّة بالأعمال السابقة.',
    stopped: 'توقف التشغيل ({detail})؛ هذا الملف جزئي.',
    failed: 'فشل التشغيل ({detail})؛ هذا الملف جزئي.',
    cancelled: 'أُلغي التشغيل؛ هذا الملف جزئي.',
    passagesNotRun: 'مراحل لم تُنفَّذ: {detail}.',
    uncheckedItems: 'عناصر لم يحكم عليها الحارس بعد، في: {detail}.',
    searchesSkipped: 'نفدت ميزانية البحث: {detail}.',
    leadsNotVerified: 'مسارات بلا حكم: {detail}.',
    noveltiesToVerify: 'جِدّة ما زالت تنتظر المقارنة بالأعمال السابقة: {detail}.',
  },
  stopReasons: {
    maxModelCalls: 'حد استدعاءات النموذج',
    timeoutMs: 'الحد الزمني',
    policy: 'سياسة الميزانية',
  },
  principle: 'المبدأ',
  principleText:
    'ملاحظة الموضوع، والدخول في آلياته، وفهم مكوّناته وتفاعلاتها. استعادة المشكلات التي كان بناؤه يجيب عنها، بوسائل عصره ومعارفه. دراسة التقدم الذي حصل منذ ذلك الحين، في مجاله وفي المجالات المجاورة. استخدام هذا الفهم لتخيّل تنظيم آخر للنظام، وتصميم التجارب التي تختبره ككل. المعرفة الثابتة تستشهد بنتيجة استُرجعت خلال هذه الدراسة؛ والفرضية معقولة لكنها غير موثّقة هنا؛ والجِدّة تُقارن بالأعمال السابقة.',
  passages: 'المراحل',
  passage: 'المرحلة',
  state: 'الحالة',
  passageNames: {
    observe: 'الملاحظة',
    decompose: 'التفكيك',
    historicalChoices: 'فهم خيارات العصر',
    changes: 'فحص ما تغيّر',
    cross: 'مقاطعة الماضي بالحاضر',
    design: 'تصميم عدة تنظيمات',
    confront: 'المواجهة',
  },
  passageStates: {
    complete: 'مكتملة',
    partial: 'جزئية',
    unchecked: 'لم يحكم عليها الحارس',
    notRun: 'لم تُنفَّذ',
  },
  collections: {
    analogues: 'اختراقات بالتجميع',
    capabilities: 'قدرات جديدة مرشحة',
    observations: 'الملاحظات',
    pieces: 'القطع ومجهولاتها',
    chain: 'السلسلة الكاملة',
    historicalChoices: 'الخيارات وظروفها',
    advances: 'التقدم منذ ذلك الحين',
    leadVerdicts: 'مسارات المستخدم بعد التحقق',
    independentLeads: 'مسارات وُجدت خارجها',
    references: 'أفضل الإنجازات الحالية',
    constraints: 'القيود',
    revisableDecisions: 'قرارات أصبحت قابلة للمراجعة',
    combinations: 'التركيبات',
    architectures: 'البُنى',
    threeStates: 'الحالات الثلاث',
    noveltyClaims: 'ما هو جديد وما ليس جديدًا',
    experiments: 'التجارب',
    cards: 'بطاقات الآليات',
  },
  kinds: { behaviour: 'سلوك', use: 'استخدام', variation: 'تنويع', failure: 'عطل' },
  conditions: 'الظروف',
  era: 'الحقبة',
  function: 'الوظيفة',
  inputs: 'المدخلات',
  outputs: 'المخرجات',
  relations: 'العلاقات',
  unknowns: 'المجهولات',
  parent: 'تفصيل لـ',
  pieces: 'القطع',
  factors: 'ظروف العصر',
  factorNames: {
    hardware: 'العتاد',
    tools: 'الأدوات',
    uses: 'الاستخدامات',
    knowledge: 'المعارف',
    costs: 'التكاليف',
    compatibility: 'التوافق',
    other: 'أخرى',
  },
  date: 'التاريخ',
  evidence: 'الدليل',
  availability: 'الإتاحة',
  otherDomain: 'من مجال آخر',
  verdicts: { relevant: 'وجيه', partlyRelevant: 'وجيه جزئيًا', notRelevant: 'غير وجيه' },
  unverifiedLead: 'بلا حكم',
  toolKinds: { mathematical: 'رياضية', technical: 'تقنية', other: 'أخرى' },
  constraintStates: { remains: 'باقية', weakened: 'ضعفت', newRequirement: 'متطلبات جديدة' },
  because: 'لأن',
  opens: 'يفتح',
  states: {
    atItsTime: 'الموضوع في عصره',
    currentBest: 'أفضل الإنجازات الحالية',
    proposal: 'اقتراحنا',
  },
  enables: 'ما يتيحه A لـ B',
  exchange: 'ما يتبادلانه',
  cost: 'ما يكلّفه',
  changes: 'يغيّر',
  changeKinds: {
    representation: 'التمثيل',
    distribution: 'توزيع العمل',
    responsibilities: 'المسؤوليات',
  },
  designLeads: 'مسارات التصميم',
  mechanism: 'الآلية',
  benefit: 'الفائدة المتوقعة',
  addedCost: 'التكلفة الإضافية',
  counterexample: 'مثال مضاد محتمل',
  chainCoverage: 'على امتداد السلسلة',
  uncovered: 'حلقات غير مغطاة',
  predictions: 'التنبؤات',
  architecture: 'البنية',
  priorArt: 'الأعمال السابقة',
  priorArtVerdicts: { novel: 'جديد', partlyNovel: 'جديد جزئيًا', exists: 'موجود بالفعل' },
  decides: 'يفاضل بين',
  protocol: 'البروتوكول',
  measures: 'القياسات',
  criteria: 'المعايير',
  expected: 'النتائج المتوقعة',
  wholeChain: 'يختبر السلسلة كاملة',
  yes: 'نعم',
  no: 'لا',
  cardFields: [
    'الملاحظة',
    'الآلية المفهومة',
    'المجهول',
    'الخيار التاريخي',
    'التطور',
    'الإمكانية الجديدة',
    'التركيبة المقترحة',
    'التنبؤ',
    'التجربة',
    'النتيجة والخطأ',
    'الخلاصة والذاكرة',
  ],
  toFill: 'يُملأ بعد إجراء التجربة',
  error: 'الخطأ',
  statuses: { established: 'ثابت', hypothesis: 'فرضية', novelty: 'جِدّة' },
  noveltyToVerify: 'جِدّة يجب التحقق منها',
  declared: 'مُعلَن',
  unchecked: 'لم يحكم عليه الحارس',
  serves: 'يخدم',
  driftLog: 'سجل الانحراف',
  driftBy: { guardian: 'خارج الهدف', schema: 'رفضه المخطط' },
  noDrift: 'لم يخرج أي عنصر عن الهدف.',
  sources: 'المصادر',
  via: 'عبر',
  noResults: 'لم تُسترجع أي نتيجة.',
  statistics: 'الإحصاءات',
  stats: {
    runs: 'مرات التشغيل',
    modelCalls: 'استدعاءات النموذج',
    searches: 'عمليات البحث',
    results: 'النتائج المسترجعة',
    items: 'العناصر',
    rejected: 'العناصر المرفوضة',
    downgraded: 'الحالات المخفّضة',
    noveltiesToVerify: 'جِدّة يجب التحقق منها',
    redos: 'مراحل أُعيدت',
    loops: 'مراحل أُعيد فتحها',
  },
  capabilityQuestion: 'أي تغيير في المبدأ يجعل ممكنًا ما هو صعب اليوم، لا مجرد أسرع؟',
  capabilityAim: 'أي تغيير في المبدأ يجعل هذا ممكنًا، وهو صعب اليوم: {capability}؟',
  capabilityAimed: 'القدرة المستهدفة',
  noCapabilityNamed: 'لم تُسمَّ: تقترح الدراسة مرشحات',
  analoguesNamed: 'اختراقات يجب تفكيكها',
  newCapability: 'القدرة الجديدة المستهدفة',
  improves: 'ما الذي يتحسن',
  forWhom: 'لمن',
  liftedConstraint: 'القيد المرفوع',
  hardToday: 'لماذا هو صعب اليوم',
  principleChange: 'تغيير المبدأ',
  principles: {
    representation: 'التمثيل',
    distribution: 'توزيع العمل',
    responsibility: 'المسؤولية',
    trust: 'الثقة',
    verification: 'ما يُتحقَّق منه',
    other: 'أخرى',
  },
  componentsAssembly: 'المكوّنات ← التجميع',
  assembly: 'التجميع',
  gives: 'يقدّم للبقية',
  capabilityOpened: 'القدرة التي انفتحت',
  pattern: 'نمط التجميع',
  components: 'المكوّنات',
  domain: 'المجال',
  arrow: '←',
  architectureKinds: { capability: 'قدرة جديدة', improvement: 'تحسين: أسرع أو أرخص' },
  judgedImprovement: 'حكم الحارس بأنها أسرع أو أرخص فقط',
  none: 'لا شيء',
};

const hi: StudyLabels = {
  sep: ': ',
  list: '; ',
  guidingQuestion:
    'यदि हमें आज की ज़रूरतों को आज उपलब्ध ज्ञान और तकनीकों से पूरा करना हो, तो हम इस वस्तु को कैसे व्यवस्थित करेंगे?',
  study: 'अध्ययन',
  charter: 'चार्टर',
  object: 'वस्तु',
  question: 'मार्गदर्शक प्रश्न',
  objective: 'उद्देश्य',
  needs: 'आज की ज़रूरतें और मानदंड',
  leads: 'उपयोगकर्ता के सुराग',
  leadsNote: 'जाँचने योग्य उदाहरण, सत्य नहीं',
  outOfScope: 'दायरे से बाहर',
  charterHash: 'चार्टर का हैश (SHA-256)',
  amendments: 'संशोधन',
  amendmentVerdicts: {
    refines: 'उद्देश्य को स्पष्ट करता है, स्वीकार',
    conflicts: 'चार्टर से टकराता है',
    changesObjective: 'उद्देश्य बदलता है',
    unclassified: 'वर्गीकृत नहीं हो सका',
  },
  refused: 'अस्वीकृत',
  notices: 'पढ़ने से पहले',
  noticeTexts: {
    analoguesNotDeconstructed: 'जिन सफलताओं को विघटित नहीं किया गया: {detail}।',
    noCapability: 'कोई आर्किटेक्चर नई क्षमता को लक्ष्य नहीं करता: डिज़ाइन केवल सुधार देता है।',
    noSources:
      'इस अध्ययन के पास कोई खोज स्रोत नहीं था: कोई दावा स्थापित नहीं हो सका, और किसी नवीनता की पूर्व कार्य से तुलना नहीं हो सकी।',
    stopped: 'रन रोका गया ({detail}); यह दस्तावेज़ अधूरा है।',
    failed: 'रन विफल हुआ ({detail}); यह दस्तावेज़ अधूरा है।',
    cancelled: 'रन रद्द किया गया; यह दस्तावेज़ अधूरा है।',
    passagesNotRun: 'जो चरण नहीं चले: {detail}।',
    uncheckedItems: 'ऐसे आइटम जिन्हें संरक्षक ने अभी नहीं जाँचा, इनमें: {detail}।',
    searchesSkipped: 'खोज का बजट समाप्त हो गया: {detail}।',
    leadsNotVerified: 'बिना निर्णय वाले सुराग: {detail}।',
    noveltiesToVerify: 'नवीनताएँ जिनकी पूर्व कार्य से तुलना अभी बाकी है: {detail}।',
  },
  stopReasons: {
    maxModelCalls: 'मॉडल कॉल की सीमा',
    timeoutMs: 'समय की सीमा',
    policy: 'बजट नीति',
  },
  principle: 'सिद्धांत',
  principleText:
    'वस्तु का अवलोकन करना, उसकी क्रियाविधियों में उतरना, उसके घटकों और उनकी पारस्परिक क्रियाओं को समझना। उन समस्याओं को फिर से खोजना जिनका उत्तर उसकी बनावट अपने समय के साधनों और ज्ञान से देती थी। तब से उसके क्षेत्र और पड़ोसी क्षेत्रों में हुई प्रगति का अध्ययन करना। इस समझ से प्रणाली के एक अलग संगठन की कल्पना करना, और उन प्रयोगों की रूपरेखा बनाना जो उसे समग्र रूप से परखें। स्थापित ज्ञान इस अध्ययन के दौरान प्राप्त किसी परिणाम का हवाला देता है; परिकल्पना विश्वसनीय है पर यहाँ प्रलेखित नहीं; नवीनता की तुलना पूर्व कार्य से की जाती है।',
  passages: 'चरण',
  passage: 'चरण',
  state: 'स्थिति',
  passageNames: {
    observe: 'अवलोकन करना',
    decompose: 'विघटित करना',
    historicalChoices: 'अपने समय के चुनाव समझना',
    changes: 'जो बदला उसकी जाँच',
    cross: 'अतीत और वर्तमान को जोड़ना',
    design: 'कई संगठन रचना',
    confront: 'परखना',
  },
  passageStates: {
    complete: 'पूर्ण',
    partial: 'आंशिक',
    unchecked: 'संरक्षक ने नहीं जाँचा',
    notRun: 'नहीं चला',
  },
  collections: {
    analogues: 'संयोजन से मिली सफलताएँ',
    capabilities: 'संभावित नई क्षमताएँ',
    observations: 'अवलोकन',
    pieces: 'हिस्से और उनके अज्ञात',
    chain: 'पूरी शृंखला',
    historicalChoices: 'चुनाव और उनकी परिस्थितियाँ',
    advances: 'तब से हुई प्रगति',
    leadVerdicts: 'उपयोगकर्ता के सुराग, जाँचे गए',
    independentLeads: 'उनसे आगे मिले सुराग',
    references: 'आज के सर्वश्रेष्ठ कार्यान्वयन',
    constraints: 'बाधाएँ',
    revisableDecisions: 'निर्णय जो अब संशोधनीय हैं',
    combinations: 'संयोजन',
    architectures: 'आर्किटेक्चर',
    threeStates: 'तीन अवस्थाएँ',
    noveltyClaims: 'क्या नया है और क्या नहीं',
    experiments: 'प्रयोग',
    cards: 'क्रियाविधि कार्ड',
  },
  kinds: { behaviour: 'व्यवहार', use: 'उपयोग', variation: 'भिन्नता', failure: 'विफलता' },
  conditions: 'परिस्थितियाँ',
  era: 'युग',
  function: 'कार्य',
  inputs: 'इनपुट',
  outputs: 'आउटपुट',
  relations: 'संबंध',
  unknowns: 'अज्ञात',
  parent: 'इसका विवरण',
  pieces: 'हिस्से',
  factors: 'उस समय की परिस्थितियाँ',
  factorNames: {
    hardware: 'हार्डवेयर',
    tools: 'उपकरण',
    uses: 'उपयोग',
    knowledge: 'ज्ञान',
    costs: 'लागत',
    compatibility: 'संगतता',
    other: 'अन्य',
  },
  date: 'तिथि',
  evidence: 'प्रमाण',
  availability: 'उपलब्धता',
  otherDomain: 'दूसरे क्षेत्र से',
  verdicts: {
    relevant: 'प्रासंगिक',
    partlyRelevant: 'आंशिक रूप से प्रासंगिक',
    notRelevant: 'प्रासंगिक नहीं',
  },
  unverifiedLead: 'कोई निर्णय नहीं',
  toolKinds: { mathematical: 'गणितीय', technical: 'तकनीकी', other: 'अन्य' },
  constraintStates: {
    remains: 'बनी हुई हैं',
    weakened: 'कमज़ोर हुई हैं',
    newRequirement: 'नई आवश्यकताएँ',
  },
  because: 'क्योंकि',
  opens: 'खोलता है',
  states: {
    atItsTime: 'अपने समय में वस्तु',
    currentBest: 'आज के सर्वश्रेष्ठ कार्यान्वयन',
    proposal: 'हमारा प्रस्ताव',
  },
  enables: 'A, B को क्या करने देता है',
  exchange: 'वे क्या आदान-प्रदान करते हैं',
  cost: 'इसकी लागत',
  changes: 'बदलता है',
  changeKinds: {
    representation: 'निरूपण',
    distribution: 'काम का बँटवारा',
    responsibilities: 'ज़िम्मेदारियाँ',
  },
  designLeads: 'डिज़ाइन की दिशाएँ',
  mechanism: 'क्रियाविधि',
  benefit: 'अपेक्षित लाभ',
  addedCost: 'अतिरिक्त लागत',
  counterexample: 'संभावित प्रति-उदाहरण',
  chainCoverage: 'पूरी शृंखला पर',
  uncovered: 'जो कड़ियाँ शामिल नहीं',
  predictions: 'पूर्वानुमान',
  architecture: 'आर्किटेक्चर',
  priorArt: 'पूर्व कार्य',
  priorArtVerdicts: { novel: 'नया', partlyNovel: 'आंशिक रूप से नया', exists: 'पहले से मौजूद' },
  decides: 'इनके बीच निर्णय',
  protocol: 'प्रोटोकॉल',
  measures: 'माप',
  criteria: 'मानदंड',
  expected: 'अपेक्षित परिणाम',
  wholeChain: 'पूरी शृंखला को परखता है',
  yes: 'हाँ',
  no: 'नहीं',
  cardFields: [
    'अवलोकन',
    'समझी गई क्रियाविधि',
    'अज्ञात',
    'ऐतिहासिक चुनाव',
    'विकास',
    'नई संभावना',
    'प्रस्तावित संयोजन',
    'पूर्वानुमान',
    'प्रयोग',
    'परिणाम और त्रुटि',
    'निष्कर्ष और स्मृति',
  ],
  toFill: 'प्रयोग के बाद भरें',
  error: 'त्रुटि',
  statuses: { established: 'स्थापित', hypothesis: 'परिकल्पना', novelty: 'नवीनता' },
  noveltyToVerify: 'जाँचने योग्य नवीनता',
  declared: 'घोषित',
  unchecked: 'संरक्षक ने नहीं जाँचा',
  serves: 'सेवा करता है',
  driftLog: 'भटकाव का लॉग',
  driftBy: { guardian: 'उद्देश्य से बाहर', schema: 'स्कीमा ने अस्वीकार किया' },
  noDrift: 'कोई आइटम उद्देश्य से नहीं भटका।',
  sources: 'स्रोत',
  via: 'के ज़रिए',
  noResults: 'कोई परिणाम प्राप्त नहीं हुआ।',
  statistics: 'आँकड़े',
  stats: {
    runs: 'रन',
    modelCalls: 'मॉडल कॉल',
    searches: 'खोजें',
    results: 'प्राप्त परिणाम',
    items: 'आइटम',
    rejected: 'अस्वीकृत आइटम',
    downgraded: 'घटाई गई स्थितियाँ',
    noveltiesToVerify: 'जाँचने योग्य नवीनताएँ',
    redos: 'दोबारा किए गए चरण',
    loops: 'फिर खोले गए चरण',
  },
  capabilityQuestion: 'सिद्धांत में कौन-सा बदलाव आज कठिन किसी चीज़ को संभव बनाएगा, केवल तेज़ नहीं?',
  capabilityAim: 'सिद्धांत में कौन-सा बदलाव इसे संभव बनाएगा, जो आज कठिन है: {capability}?',
  capabilityAimed: 'लक्षित क्षमता',
  noCapabilityNamed: 'कोई नाम नहीं: अध्ययन उम्मीदवार प्रस्तावित करता है',
  analoguesNamed: 'विघटित करने योग्य सफलताएँ',
  newCapability: 'लक्षित नई क्षमता',
  improves: 'क्या बेहतर होता है',
  forWhom: 'किसके लिए',
  liftedConstraint: 'हटाई गई बाधा',
  hardToday: 'आज यह कठिन क्यों है',
  principleChange: 'सिद्धांत में बदलाव',
  principles: {
    representation: 'निरूपण',
    distribution: 'काम का बँटवारा',
    responsibility: 'ज़िम्मेदारी',
    trust: 'भरोसा',
    verification: 'जिसकी जाँच होती है',
    other: 'अन्य',
  },
  componentsAssembly: 'घटक → संयोजन',
  assembly: 'संयोजन',
  gives: 'दूसरों को देता है',
  capabilityOpened: 'खुली क्षमता',
  pattern: 'संयोजन का पैटर्न',
  components: 'घटक',
  domain: 'क्षेत्र',
  arrow: '→',
  architectureKinds: { capability: 'नई क्षमता', improvement: 'सुधार: तेज़ या सस्ता' },
  judgedImprovement: 'संरक्षक ने इसे केवल तेज़ या सस्ता माना',
  none: 'कोई नहीं',
};

const LABELS: Record<StudyLabelLanguage, StudyLabels> = {
  en,
  fr,
  es,
  de,
  pt,
  ja,
  zh,
  ko,
  ru,
  ar,
  hi,
};

/** The labels' language of a language tag: `fr-CA` is `fr`; an unknown language is `en`. */
export function labelLanguage(language: string): StudyLabelLanguage {
  const primary = language.split('-')[0]?.toLowerCase() ?? 'en';
  return primary in LABELS ? (primary as StudyLabelLanguage) : 'en';
}

export function studyLabels(language: string): StudyLabels {
  return LABELS[labelLanguage(language)];
}

/**
 * The default question of a study: the method's guiding question, and the aim of a new
 * capability, the one the charter names or one to find.
 */
export function guidingQuestion(language: string, capability?: string): string {
  const labels = studyLabels(language);
  const aim = capability
    ? labels.capabilityAim.replace('{capability}', capability)
    : labels.capabilityQuestion;
  return `${labels.guidingQuestion} ${aim}`;
}
